### ISSUE TITLE
UChat [ Crash quando envia mensagens ]

### ISSUE THREAD

**Issue by iPokenWIGGLE** [FabioZumbi12/UltimateChat#1]
For input string: "R"
        at java.lang.NumberFormatException.forInputString(Unknown Source) ~[?:1.8.0_92]
        at java.lang.Integer.parseInt(Unknown Source) ~[?:1.8.0_92]
        at java.lang.Integer.parseInt(Unknown Source) ~[?:1.8.0_92]
        at br.net.fabiozumbi12.UltimateChat.Fanciful.FancyMessage.createChatPacket(FancyMessage.java:659) ~[UltimateChat.jar:?]
        at br.net.fabiozumbi12.UltimateChat.Fanciful.FancyMessage.send(FancyMessage.java:632) [UltimateChat.jar:?]
        at br.net.fabiozumbi12.UltimateChat.Fanciful.FancyMessage.send(FancyMessage.java:697) [UltimateChat.jar:?]
        at br.net.fabiozumbi12.UltimateChat.UCMessages.sendFancyMessage(UCMessages.java:250) [UltimateChat.jar:?]
        at br.net.fabiozumbi12.UltimateChat.UCMessages.sendMessage(UCMessages.java:145) [UltimateChat.jar:?]
        at br.net.fabiozumbi12.UltimateChat.UCMessages.sendFancyMessage(UCMessages.java:99) [UltimateChat.jar:?]
        at br.net.fabiozumbi12.UltimateChat.UCListener.onChat(UCListener.java:420) [UltimateChat.jar:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_92]
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_92]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_92]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_92]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) [spigot.jar:git-Spigot-6016ac7-d5ecbd0]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) [spigot.jar:git-Spigot-6016ac7-d5ecbd0]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot.jar:git-Spigot-6016ac7-d5ecbd0]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:484) [spigot.jar:git-Spigot-6016ac7-d5ecbd0]
        at net.minecraft.server.v1_10_R1.PlayerConnection.chat(PlayerConnection.java:1270) [spigot.jar:git-Spigot-6016ac7-d5ecbd0]
        at net.minecraft.server.v1_10_R1.PlayerConnection.a(PlayerConnection.java:1208) [spigot.jar:git-Spigot-6016ac7-d5ecbd0]
        at net.minecraft.server.v1_10_R1.PacketPlayInChat$1.run(PacketPlayInChat.java:39) [spigot.jar:git-Spigot-6016ac7-d5ecbd0]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_92]
        at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_92]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.8.0_92]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.8.0_92]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_92]

**Comment by FabioZumbi12** [comment]
Atualizou pra ultima versão que postei hoje? Ela corrige isso.

**Comment by iPokenWIGGLE** [comment]
A vlw , quando eu mandei esse ticket , foi quando eu baixei , mas agora ta funcionando o de antes não tava ...

**Comment by FabioZumbi12** [comment]
Beleza ^^
