### ISSUE TITLE
Crash plugin with /chat reload

### ISSUE THREAD

**Issue by goga133** [FabioZumbi12/UltimateChat#118]
Plataform:  Sponge Forge old
Jar version:  1.8.6
Minecraft version:  1.12.2
Crash plugin when i will write /chat reload even without changes in config. This problem was not in 1.8.5
Error:
> [22:28:16] [Server thread/INFO] [nucleus]: goga133 ran the command: /chat reload
[22:28:16] [Server thread/INFO] [net.minecraft.server.dedicated.DedicatedServer]: UltimateChat: [-> Config module§r§r]§r
[22:28:16] [Server thread/INFO] [net.minecraft.server.dedicated.DedicatedServer]: UltimateChat: [All configurations loaded!§r§r]§r
[22:28:16] [Server thread/INFO] [net.minecraft.server.dedicated.DedicatedServer]: UltimateChat: [Language file loaded - Using: EN-US§r§r]§r
[22:28:16] [Server thread/INFO] [net.minecraft.server.dedicated.DedicatedServer]: UltimateChat: [Sponge version 7.1.0-SNAPSHOT-a312749§r§r]§r
[22:28:16] [Server thread/INFO] [net.minecraft.server.dedicated.DedicatedServer]: UltimateChat: [Permissions set for API 7 and 8§r§r]§r
[22:28:16] [Server thread/INFO] [STDERR]: [br.net.fabiozumbi12.UltimateChat.Sponge.UCCommands:lambda$uchat$11:601]: java.lang.NullPointerException
[22:28:16] [Server thread/INFO] [STDERR]: [br.net.fabiozumbi12.UltimateChat.Sponge.UCCommands:lambda$uchat$11:601]: 	at br.net.fabiozumbi12.UltimateChat.Sponge.UChat.getDefChannel(UChat.java:377)
[22:28:16] [Server thread/INFO] [STDERR]: [br.net.fabiozumbi12.UltimateChat.Sponge.UCCommands:lambda$uchat$11:601]: 	at br.net.fabiozumbi12.UltimateChat.Sponge.UChat.getPlayerChannel(UChat.java:404)
[22:28:16] [Server thread/INFO] [STDERR]: [br.net.fabiozumbi12.UltimateChat.Sponge.UCCommands:lambda$uchat$11:601]: 	at br.net.fabiozumbi12.UltimateChat.Sponge.config.UCLang.get(UCLang.java:96)
[22:28:16] [Server thread/INFO] [STDERR]: [br.net.fabiozumbi12.UltimateChat.Sponge.UCCommands:lambda$uchat$11:601]: 	at br.net.fabiozumbi12.UltimateChat.Sponge.config.UCLang.sendMessage(UCLang.java:128)
[22:28:16] [Server thread/INFO] [STDERR]: [br.net.fabiozumbi12.UltimateChat.Sponge.UCCommands:lambda$uchat$11:601]: 	at br.net.fabiozumbi12.UltimateChat.Sponge.UCCommands.lambda$uchat$11(UCCommands.java:599)
[22:28:16] [Server thread/INFO] [STDERR]: [br.net.fabiozumbi12.UltimateChat.Sponge.UCCommands:lambda$uchat$11:601]: 	at org.spongepowered.api.command.args.ChildCommandElementExecutor.execute(ChildCommandElementExecutor.java:255)
[22:28:16] [Server thread/INFO] [STDERR]: [br.net.fabiozumbi12.UltimateChat.Sponge.UCCommands:lambda$uchat$11:601]: 	at org.spongepowered.api.command.spec.CommandSpec.process(CommandSpec.java:388)
[22:28:16] [Server thread/INFO] [STDERR]: [br.net.fabiozumbi12.UltimateChat.Sponge.UCCommands:lambda$uchat$11:601]: 	at org.spongepowered.api.command.dispatcher.SimpleDispatcher.process(SimpleDispatcher.java:341)
[22:28:16] [Server thread/INFO] [STDERR]: [br.net.fabiozumbi12.UltimateChat.Sponge.UCCommands:lambda$uchat$11:601]: 	at org.spongepowered.common.command.SpongeCommandManager.process(SpongeCommandManager.java:328)
[22:28:16] [Server thread/INFO] [STDERR]: [br.net.fabiozumbi12.UltimateChat.Sponge.UCCommands:lambda$uchat$11:601]: 	at net.minecraft.command.ServerCommandManager.func_71556_a(SourceFile:1083)
[22:28:16] [Server thread/INFO] [STDERR]: [br.net.fabiozumbi12.UltimateChat.Sponge.UCCommands:lambda$uchat$11:601]: 	at net.minecraft.network.NetHandlerPlayServer.func_147361_d(NetHandlerPlayServer.java:958)
[22:28:16] [Server thread/INFO] [STDERR]: [br.net.fabiozumbi12.UltimateChat.Sponge.UCCommands:lambda$uchat$11:601]: 	at net.minecraft.network.NetHandlerPlayServer.func_147354_a(NetHandlerPlayServer.java:937)
[22:28:16] [Server thread/INFO] [STDERR]: [br.net.fabiozumbi12.UltimateChat.Sponge.UCCommands:lambda$uchat$11:601]: 	at net.minecraft.network.play.client.CPacketChatMessage.func_148833_a(SourceFile:37)
[22:28:16] [Server thread/INFO] [STDERR]: [br.net.fabiozumbi12.UltimateChat.Sponge.UCCommands:lambda$uchat$11:601]: 	at net.minecraft.network.play.client.CPacketChatMessage.func_148833_a(SourceFile:9)
[22:28:16] [Server thread/INFO] [STDERR]: [br.net.fabiozumbi12.UltimateChat.Sponge.UCCommands:lambda$uchat$11:601]: 	at org.spongepowered.common.network.PacketUtil.onProcessPacket(PacketUtil.java:149)
[22:28:16] [Server thread/INFO] [STDERR]: [br.net.fabiozumbi12.UltimateChat.Sponge.UCCommands:lambda$uchat$11:601]: 	at net.minecraft.network.PacketThreadUtil$1.redirect$onProcessPacket$zlb000(SourceFile:539)
[22:28:16] [Server thread/INFO] [STDERR]: [br.net.fabiozumbi12.UltimateChat.Sponge.UCCommands:lambda$uchat$11:601]: 	at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13)
[22:28:16] [Server thread/INFO] [STDERR]: [br.net.fabiozumbi12.UltimateChat.Sponge.UCCommands:lambda$uchat$11:601]: 	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
[22:28:16] [Server thread/INFO] [STDERR]: [br.net.fabiozumbi12.UltimateChat.Sponge.UCCommands:lambda$uchat$11:601]: 	at java.util.concurrent.FutureTask.run(Unknown Source)
[22:28:16] [Server thread/INFO] [STDERR]: [br.net.fabiozumbi12.UltimateChat.Sponge.UCCommands:lambda$uchat$11:601]: 	at net.minecraft.util.Util.func_181617_a(SourceFile:46)
[22:28:16] [Server thread/INFO] [STDERR]: [br.net.fabiozumbi12.UltimateChat.Sponge.UCCommands:lambda$uchat$11:601]: 	at org.spongepowered.common.SpongeImplHooks.onUtilRunTask(SpongeImplHooks.java:276)
[22:28:16] [Server thread/INFO] [STDERR]: [br.net.fabiozumbi12.UltimateChat.Sponge.UCCommands:lambda$uchat$11:601]: 	at net.minecraft.server.MinecraftServer.redirect$onRun$zjg000(MinecraftServer.java:3977)
[22:28:16] [Server thread/INFO] [STDERR]: [br.net.fabiozumbi12.UltimateChat.Sponge.UCCommands:lambda$uchat$11:601]: 	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:721)
[22:28:16] [Server thread/INFO] [STDERR]: [br.net.fabiozumbi12.UltimateChat.Sponge.UCCommands:lambda$uchat$11:601]: 	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:396)
[22:28:16] [Server thread/INFO] [STDERR]: [br.net.fabiozumbi12.UltimateChat.Sponge.UCCommands:lambda$uchat$11:601]: 	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:666)
[22:28:16] [Server thread/INFO] [STDERR]: [br.net.fabiozumbi12.UltimateChat.Sponge.UCCommands:lambda$uchat$11:601]: 	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524)
[22:28:16] [Server thread/INFO] [STDERR]: [br.net.fabiozumbi12.UltimateChat.Sponge.UCCommands:lambda$uchat$11:601]: 	at java.lang.Thread.run(Unknown Source)
[22:28:20] [Server thread/ERROR] [Sponge]: Could not pass MessageChannelEvent$Chat$Impl to Plugin{id=ultimatechat, name=UltimateChat, version=1.8.6, description=Complete and advanced chat plugin, authors=[FabioZumbi12], source=C:\Users\Администратор\Desktop\Сервер\server\mods\UltimateChat-1.8.6-b180-Universal.jar}
java.lang.NullPointerException: null
	at br.net.fabiozumbi12.UltimateChat.Sponge.UChat.getDefChannel(UChat.java:377) ~[UChat.class:?]
	at br.net.fabiozumbi12.UltimateChat.Sponge.UChat.getPlayerChannel(UChat.java:404) ~[UChat.class:?]
	at br.net.fabiozumbi12.UltimateChat.Sponge.UCListener.onChat(UCListener.java:115) ~[UCListener.class:?]
	at org.spongepowered.common.event.listener.ChatListener_UCListener_onChat153.handle(Unknown Source) ~[?:?]
	at org.spongepowered.common.event.RegisteredListener.handle(RegisteredListener.java:95) ~[RegisteredListener.class:1.12.2-2655-7.1.0-BETA-3025]
	at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:335) [SpongeModEventManager.class:1.12.2-2655-7.1.0-BETA-3025]
	at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:282) [SpongeModEventManager.class:1.12.2-2655-7.1.0-BETA-3025]
	at net.minecraftforge.fml.common.eventhandler.EventBus.postForgeAndCreateSpongeEvent(EventBus.java:599) [EventBus.class:?]
	at net.minecraft.network.NetHandlerPlayServer.handler$injectChatEvent$bap000(NetHandlerPlayServer.java:2763) [pa.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_147354_a(NetHandlerPlayServer.java:942) [pa.class:?]
	at net.minecraft.network.play.client.CPacketChatMessage.func_148833_a(SourceFile:37) [la.class:?]
	at net.minecraft.network.play.client.CPacketChatMessage.func_148833_a(SourceFile:9) [la.class:?]
	at org.spongepowered.common.network.PacketUtil.onProcessPacket(PacketUtil.java:149) [PacketUtil.class:1.12.2-2655-7.1.0-BETA-3025]
	at net.minecraft.network.PacketThreadUtil$1.redirect$onProcessPacket$zlb000(SourceFile:539) [hv$1.class:?]
	at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) [hv$1.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_161]
	at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_161]
	at net.minecraft.util.Util.func_181617_a(SourceFile:46) [h.class:?]
	at org.spongepowered.common.SpongeImplHooks.onUtilRunTask(SpongeImplHooks.java:276) [SpongeImplHooks.class:1.12.2-2655-7.1.0-BETA-3025]
	at net.minecraft.server.MinecraftServer.redirect$onRun$zjg000(MinecraftServer.java:3977) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:721) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:396) [nz.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:666) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_161]

**Comment by FabioZumbi12** [comment]
Seems you have set the default channel for an inexistent channel. Check your configs for options named `default-channel`.

**Comment by goga133** [comment]
I did not even change the configuration, put the plugin and immediately ordered this command, in the previous version this was not. And if I reboot the server, everything works fine. And dint work mentions (@)

**Comment by Mahavo** [comment]
I can confirm i also get this error on chat reload.

**Comment by FabioZumbi12** [comment]
Fixed on newer versions of uchat.
