### ISSUE TITLE
Bump!

### ISSUE THREAD

**Issue by vnvyvu** [FabioZumbi12/UltimateChat#133]
[17:51:05 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'uchat' in plugin UltimateChat v1.8.5
at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[spigot.jar:git-Spigot-6016ac7-10c10b3]
at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[spigot.jar:git-Spigot-6016ac7-10c10b3]
at org.bukkit.craftbukkit.v1_10_R1.CraftServer.dispatchCommand(CraftServer.java:646) ~[spigot.jar:git-Spigot-6016ac7-10c10b3]
at net.minecraft.server.v1_10_R1.PlayerConnection.handleCommand(PlayerConnection.java:1348) [spigot.jar:git-Spigot-6016ac7-10c10b3]
at net.minecraft.server.v1_10_R1.PlayerConnection.a(PlayerConnection.java:1183) [spigot.jar:git-Spigot-6016ac7-10c10b3]
at net.minecraft.server.v1_10_R1.PacketPlayInChat.a(PacketPlayInChat.java:45) [spigot.jar:git-Spigot-6016ac7-10c10b3]
at net.minecraft.server.v1_10_R1.PacketPlayInChat.a(PacketPlayInChat.java:1) [spigot.jar:git-Spigot-6016ac7-10c10b3]
at net.minecraft.server.v1_10_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot.jar:git-Spigot-6016ac7-10c10b3]
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_171]
at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_171]
at net.minecraft.server.v1_10_R1.SystemUtils.a(SourceFile:45) [spigot.jar:git-Spigot-6016ac7-10c10b3]
at net.minecraft.server.v1_10_R1.MinecraftServer.D(MinecraftServer.java:733) [spigot.jar:git-Spigot-6016ac7-10c10b3]
at net.minecraft.server.v1_10_R1.DedicatedServer.D(DedicatedServer.java:399) [spigot.jar:git-Spigot-6016ac7-10c10b3]
at net.minecraft.server.v1_10_R1.MinecraftServer.C(MinecraftServer.java:672) [spigot.jar:git-Spigot-6016ac7-10c10b3]
at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:571) [spigot.jar:git-Spigot-6016ac7-10c10b3]
at java.lang.Thread.run(Unknown Source) [?:1.8.0_171]
Caused by: java.lang.NullPointerException
at br.net.fabiozumbi12.UltimateChat.Bukkit.UCPerms.channelReadPerm(UCPerms.java:44) ~[?:?]
at br.net.fabiozumbi12.UltimateChat.Bukkit.UCListener.sendHelp(UCListener.java:927) ~[?:?]
at br.net.fabiozumbi12.UltimateChat.Bukkit.UCListener.onCommand(UCListener.java:36) ~[?:?]
at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[spigot.jar:git-Spigot-6016ac7-10c10b3]
... 15 more

**Comment by FabioZumbi12** [comment]
You totally is not using the issue template and title...

Use the latest version available on template issue and on this github home page (1.8.6) and try again.
