### ISSUE TITLE
[Spigot] 1.13 startup issue due to Bungeecord

### ISSUE THREAD

**Issue by danjono** [FabioZumbi12/UltimateChat#146]
==> Click on PREVIEW tab!

### Before open an issue, checkout this steps:
* If you are running the plugin at first time, try to run again to see if the problem persists.
* Check if your build is the latest on our Jenkins. Click Here: <https://host.areaz12server.net.br:8080/job/UltimateChat>
* Its important to you include the plugin jar name, because version and build info.

_Put if is the **Spigot** or **Sponge** version._  
Platform: Spigot

_Inform your UltimateChat jar name like **UltimateChat-Spigot-7.0.3.jar**._  
Jar version:  UltimateChat-1.8.6-b183

_Your server Minecraft version_  
Minecraft version: 1.13

_Issue or Suggestion?_  
What you want?:  Issue

_Describe your issue/Suggestion. If issue, use the site [hastebin.com](https://hastebin.com/) to put your error or console logs._
Description:  

In the latest Spigot 1.13 jar the console is stating the following on startup.

`[15:36:10 WARN]: java.lang.IllegalArgumentException: Channel must contain : separator
[15:36:10 WARN]:        at org.bukkit.plugin.messaging.StandardMessenger.validateAndCorrectChannel(StandardMessenger.java:474)
[15:36:10 WARN]:        at org.bukkit.plugin.messaging.StandardMessenger.registerOutgoingPluginChannel(StandardMessenger.java:180)
[15:36:10 WARN]:        at br.net.fabiozumbi12.UltimateChat.Bukkit.UChat.onEnable(UChat.java:169)
[15:36:10 WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
[15:36:10 WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:339)
[15:36:10 WARN]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:403)
[15:36:10 WARN]:        at org.bukkit.craftbukkit.v1_13_R1.CraftServer.enablePlugin(CraftServer.java:424)
[15:36:10 WARN]:        at org.bukkit.craftbukkit.v1_13_R1.CraftServer.enablePlugins(CraftServer.java:338)
[15:36:10 WARN]:        at net.minecraft.server.v1_13_R1.MinecraftServer.m(MinecraftServer.java:562)
[15:36:10 WARN]:        at net.minecraft.server.v1_13_R1.MinecraftServer.g_(MinecraftServer.java:524)
[15:36:10 WARN]:        at net.minecraft.server.v1_13_R1.MinecraftServer.a(MinecraftServer.java:423)
[15:36:10 WARN]:        at net.minecraft.server.v1_13_R1.DedicatedServer.init(DedicatedServer.java:288)
[15:36:10 WARN]:        at net.minecraft.server.v1_13_R1.MinecraftServer.run(MinecraftServer.java:686)
[15:36:10 WARN]:        at java.lang.Thread.run(Thread.java:748)
`

The fix is to rename your messaging channel to the Bungeecord proxy. The requirement now is for the channel name to have a colon and no capital letters where currently it is set to "uChat"

**Comment by FabioZumbi12** [comment]
Try the latest build from our jenkins.

**Comment by danjono** [comment]
[Jenkins](https://host.areaz12server.net.br:8080/job/UltimateChat/) server appears to be unreachable.

**Comment by danjono** [comment]
Looking at your changes I don't think it will work just yet. The channel names also need to be updated to the new name in UltimateChat-Bungee.

**Comment by danjono** [comment]
Any update with this? Even with the Jenkins server coming back online it didn't build the last commit.

**Comment by FabioZumbi12** [comment]
Jenkins is online, only with a warning about certificate.

Try the latest build: https://host.areaz12server.net.br:8080/job/UltimateChat/194/artifact/UltimateChat-Sponge-78/target/UltimateChat-1.8.6-b194-Universal.jar
