### ISSUE TITLE
Sponge (SpongeForge): Error - No such Method > [Player Interface] "getItemInHand

### ISSUE THREAD

**Issue by rouing** [FabioZumbi12/UltimateChat#151]
Platform: Sponge

_Inform your UltimateChat jar name like **UltimateChat-Spigot-7.0.3.jar**._  
Jar version:  Sponge b195

_Your server Minecraft version_  
Minecraft version:  1.12.2
```

> [10:56:21] [Server thread/ERROR] [Sponge]: Error occurred while executing command 'l' for source EntityPlayerMP['Rouing'/900, l='world', x=316.03, y=66.00, z=509.59]: org.spongepowered.api.entity.living.player.Player.getItemInHand(Lorg/spongepowered/api/data/type/HandType;)Lorg/spongepowered/api/item/inventory/ItemStack;
java.lang.NoSuchMethodError: org.spongepowered.api.entity.living.player.Player.getItemInHand(Lorg/spongepowered/api/data/type/HandType;)Lorg/spongepowered/api/item/inventory/ItemStack;
at br.net.fabiozumbi12.UltimateChat.Sponge.UCVHelper78.getItemInHand(UCVHelper78.java:36) ~[UCVHelper78.class:?]
at br.net.fabiozumbi12.UltimateChat.Sponge.UCMessages.formatTags(UCMessages.java:602) ~[UCMessages.class:?]
at br.net.fabiozumbi12.UltimateChat.Sponge.config.UCLang.get(UCLang.java:96) ~[UCLang.class:?]
at br.net.fabiozumbi12.UltimateChat.Sponge.config.UCLang.sendMessage(UCLang.java:124) ~[UCLang.class:?]
at br.net.fabiozumbi12.UltimateChat.Sponge.UCCommands.addPlayerToChannel(UCCommands.java:423) ~[UCCommands.class:?]
at br.net.fabiozumbi12.UltimateChat.Sponge.UCCommands.lambda$registerChannelAlias$5(UCCommands.java:444) ~[UCCommands.class:?]
at org.spongepowered.api.command.spec.CommandSpec.process(CommandSpec.java:388) ~[CommandSpec.class:1.12.2-2705-7.1.0-BETA-3206]
at org.spongepowered.api.command.dispatcher.SimpleDispatcher.process(SimpleDispatcher.java:341) ~[SimpleDispatcher.class:1.12.2-2705-7.1.0-BETA-3206]
at org.spongepowered.common.command.SpongeCommandManager.process(SpongeCommandManager.java:328) [SpongeCommandManager.class:1.12.2-2705-7.1.0-BETA-3206]
at net.minecraft.command.ServerCommandManager.func_71556_a(SourceFile:1083) [dh.class:?]
at net.minecraft.network.NetHandlerPlayServer.func_147361_d(NetHandlerPlayServer.java:958) [pa.class:?]
at net.minecraft.network.NetHandlerPlayServer.func_147354_a(NetHandlerPlayServer.java:937) [pa.class:?]
at net.minecraft.network.play.client.CPacketChatMessage.func_148833_a(SourceFile:37) [la.class:?]
at net.minecraft.network.play.client.CPacketChatMessage.func_148833_a(SourceFile:9) [la.class:?]
at org.spongepowered.common.network.PacketUtil.onProcessPacket(PacketUtil.java:148) [PacketUtil.class:1.12.2-2705-7.1.0-BETA-3206]
at net.minecraft.network.PacketThreadUtil$1.redirect$onProcessPacket$zlg000(SourceFile:539) [hv$1.class:?]
at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) [hv$1.class:?]
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_171]
at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_171]
at net.minecraft.util.Util.func_181617_a(SourceFile:46) [h.class:?]
at org.spongepowered.common.SpongeImplHooks.onUtilRunTask(SpongeImplHooks.java:288) [SpongeImplHooks.class:1.12.2-2705-7.1.0-BETA-3206]
at net.minecraft.server.MinecraftServer.redirect$onRun$zjl000(MinecraftServer.java:3987) [MinecraftServer.class:?]
at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:723) [MinecraftServer.class:?]
at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:396) [nz.class:?]
at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668) [MinecraftServer.class:?]
at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_171] 
```

**Comment by rouing** [comment]
I've rolled back to the previous version and now it works fine. Ive tagged the breaking commit and the file is here:

https://github.com/FabioZumbi12/UltimateChat/blob/master/UltimateChat-Sponge-78/src/main/java/br/net/fabiozumbi12/UltimateChat/Sponge/UCVHelper78.java

**Comment by FabioZumbi12** [comment]
Ive updated to api 8 but i still need to add a helper class for api7 because diffs on 7 and 8

**Comment by rouing** [comment]
I figured this was the case.

Now things get dicey.

**Comment by FabioZumbi12** [comment]
Updated. Download the latest from sponge ore ;)

**Comment by rouing** [comment]
Ill give it a shot. Thanks

**Comment by rouing** [comment]
Resolved so far. I will report back with testing.
Closing for now.
