### ISSUE TITLE
Error in console after uchat reload

### ISSUE THREAD

**Issue by comonier** [FabioZumbi12/UltimateChat#161]
https://hastebin.com/ihabakuhoz.cs
on game:
An internal error occurred while attempting to perform this command

**Comment by comonier** [comment]
https://hastebin.com/ocirakawiq.apache

**Comment by eltonnikecasa** [comment]
Version java 8, Debian 9, UltimateChat-1.8.8-b202-Universal.jar

mesmo problema no meu, tanto dentro do jogo como no console, não consigo dar o comando /uchat reload.

log:
> uchat reload
[07:40:45 INFO]: UltimateChat: [All configurations loaded!]
[07:40:45 INFO]: UltimateChat: [Language file loaded - Using: PT-BR]
[07:40:45 WARN]: Unexpected exception while parsing console command "uchat reload"
org.bukkit.command.CommandException: Unhandled exception executing command 'uchat' in plugin UltimateChat v1.8.8
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[patched_1.13.2.jar:git-Paper-495]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:149) ~[patched_1.13.2.jar:git-Paper-495]
        at org.bukkit.craftbukkit.v1_13_R2.CraftServer.dispatchCommand(CraftServer.java:732) ~[patched_1.13.2.jar:git-Paper-495]
        at org.bukkit.craftbukkit.v1_13_R2.CraftServer.dispatchServerCommand(CraftServer.java:694) ~[patched_1.13.2.jar:git-Paper-495]
        at net.minecraft.server.v1_13_R2.DedicatedServer.handleCommandQueue(DedicatedServer.java:483) ~[patched_1.13.2.jar:git-Paper-495]
        at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:440) ~[patched_1.13.2.jar:git-Paper-495]
        at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:938) ~[patched_1.13.2.jar:git-Paper-495]
        at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:836) ~[patched_1.13.2.jar:git-Paper-495]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_191]
Caused by: java.lang.NullPointerException
        at br.net.fabiozumbi12.UltimateChat.Bukkit.UChat.registerAliases(UChat.java:461) ~[?:?]
        at br.net.fabiozumbi12.UltimateChat.Bukkit.UChat.registerAliases(UChat.java:450) ~[?:?]
        at br.net.fabiozumbi12.UltimateChat.Bukkit.UChat.reload(UChat.java:298) ~[?:?]
        at br.net.fabiozumbi12.UltimateChat.Bukkit.UCListener.onCommand(UCListener.java:154) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[patched_1.13.2.jar:git-Paper-495]
        ... 8 more
