### ISSUE TITLE
Problemas de compatibilidade com o MCClans

### ISSUE THREAD

**Issue by superteits** [FabioZumbi12/UltimateChat#18]
Olá Fabio, estou utilizando seu plugin no meu servidor, tenho instalado o plugin MCClans e nas configurações do UltimateChat sempre que permito o Hook do MCClans esse erro ocorre quando alguém fala no chat:

```
[Sponge]: Could not pass MessageChannelEvent$Chat$Impl to Plugin{id=ultimatechat, name=UltimateChat, version=1.7.1, description=Complete and advanced chat plugin, authors=[FabioZumbi12], source=/home/servers/Pixelmon5/mods/UltimateChat-1.7.1-b22.jar}
java.lang.NullPointerException
        at br.net.fabiozumbi12.UltimateChat.UCMessages.formatTags(UCMessages.java:502) ~[UCMessages.class:?]
        at br.net.fabiozumbi12.UltimateChat.UCMessages.sendMessage(UCMessages.java:334) ~[UCMessages.class:?]
        at br.net.fabiozumbi12.UltimateChat.UCMessages.sendFancyMessage(UCMessages.java:123) ~[UCMessages.class:?]
        at br.net.fabiozumbi12.UltimateChat.UCListener.onChat(UCListener.java:64) ~[UCListener.class:?]
        at org.spongepowered.common.event.listener.ChatListener_UCListener_onChat207.handle(Unknown Source) ~[?:?]
        at org.spongepowered.common.event.RegisteredListener.handle(RegisteredListener.java:95) ~[RegisteredListener.class:1.10.2-2281-5.2.0-BETA-2274]
        at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:313) ~[SpongeModEventManager.class:1.10.2-2281-5.2.0-BETA-2274]
        at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:271) ~[SpongeModEventManager.class:1.10.2-2281-5.2.0-BETA-2274]
        at net.minecraftforge.fml.common.eventhandler.EventBus.postForgeAndCreateSpongeEvent(EventBus.java:598) ~[EventBus.class:?]
        at net.minecraft.network.NetHandlerPlayServer.handler$injectChatEvent$zom000(NetHandlerPlayServer.java:2532) ~[me.class:?]
        at net.minecraft.network.NetHandlerPlayServer.func_147354_a(NetHandlerPlayServer.java:897) ~[me.class:?]
        at net.minecraft.network.play.client.CPacketChatMessage.func_148833_a(SourceFile:37) ~[im.class:?]
        at net.minecraft.network.play.client.CPacketChatMessage.func_148833_a(SourceFile:9) ~[im.class:?]
        at org.spongepowered.common.network.PacketUtil.lambda$onProcessPacket$0(PacketUtil.java:157) ~[PacketUtil.class:1.10.2-2281-5.2.0-BETA-2274]
        at org.spongepowered.common.event.tracking.CauseTracker.switchToPhase(CauseTracker.java:160) [CauseTracker.class:1.10.2-2281-5.2.0-BETA-2274]
        at org.spongepowered.common.network.PacketUtil.onProcessPacket(PacketUtil.java:156) [PacketUtil.class:1.10.2-2281-5.2.0-BETA-2274]
        at net.minecraft.network.PacketThreadUtil$1.redirect$onProcessPacket$zjh000(SourceFile:539) [fl$1.class:?]
        at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) [fl$1.class:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_121]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_121]
        at net.minecraft.util.Util.func_181617_a(SourceFile:45) [h.class:?]
        at org.spongepowered.common.SpongeImplHooks.onUtilRunTask(SpongeImplHooks.java:241) [SpongeImplHooks.class:1.10.2-2281-5.2.0-BETA-2274]
        at net.minecraft.server.MinecraftServer.redirect$onRun$zhn000(MinecraftServer.java:3928) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:668) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:387) [ld.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]
```
A formatação do chat fica da seguinte maneira:
http://prntscr.com/f01hk1

**Comment by FabioZumbi12** [comment]
Acho que arrumei na ultima build, baixa daqui: http://158.69.121.149:8080/job/UltimateChat/

**Comment by superteits** [comment]
Obrigado por responder, testei a build UltimateChat-Sponge-1.7.1-b33.jar e o seguinte erro ocorre ao ligar o servidor:

```
[14:25:34] [Server thread/INFO]: UltimateChat: [-> Config module]
[14:25:34] [Server thread/INFO]: UltimateChat: [All configurations loaded!]
[14:25:34] [Server thread/INFO]: UltimateChat: [Language file loaded - Using: EN-US]
[14:25:34] [Server thread/INFO]: UltimateChat: [Init commands module...]
[14:25:34] [Server thread/INFO] [STDERR]: [br.net.fabiozumbi12.UltimateChat.UChat:onServerStart:121]: java.lang.NullPointerException
[14:25:34] [Server thread/INFO] [STDERR]: [br.net.fabiozumbi12.UltimateChat.UChat:onServerStart:121]:   at br.net.fabiozumbi12.UltimateChat.UCCommands.registerChannelAliases(UCCommands.java:213)
[14:25:34] [Server thread/INFO] [STDERR]: [br.net.fabiozumbi12.UltimateChat.UChat:onServerStart:121]:   at br.net.fabiozumbi12.UltimateChat.UCCommands.<init>(UCCommands.java:31)
[14:25:34] [Server thread/INFO] [STDERR]: [br.net.fabiozumbi12.UltimateChat.UChat:onServerStart:121]:   at br.net.fabiozumbi12.UltimateChat.UChat.onServerStart(UChat.java:108)
[14:25:34] [Server thread/INFO] [STDERR]: [br.net.fabiozumbi12.UltimateChat.UChat:onServerStart:121]:   at org.spongepowered.common.event.listener.GameStartedServerEventListener_UChat_onServerStart58.handle(Unknown Source)
[14:25:34] [Server thread/INFO] [STDERR]: [br.net.fabiozumbi12.UltimateChat.UChat:onServerStart:121]:   at org.spongepowered.common.event.RegisteredListener.handle(RegisteredListener.java:95)
[14:25:34] [Server thread/INFO] [STDERR]: [br.net.fabiozumbi12.UltimateChat.UChat:onServerStart:121]:   at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:313)
[14:25:34] [Server thread/INFO] [STDERR]: [br.net.fabiozumbi12.UltimateChat.UChat:onServerStart:121]:   at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:342)
[14:25:34] [Server thread/INFO] [STDERR]: [br.net.fabiozumbi12.UltimateChat.UChat:onServerStart:121]:   at org.spongepowered.mod.SpongeMod.onStateEvent(SpongeMod.java:234)
[14:25:34] [Server thread/INFO] [STDERR]: [br.net.fabiozumbi12.UltimateChat.UChat:onServerStart:121]:   at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[14:25:34] [Server thread/INFO] [STDERR]: [br.net.fabiozumbi12.UltimateChat.UChat:onServerStart:121]:   at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[14:25:34] [Server thread/INFO] [STDERR]: [br.net.fabiozumbi12.UltimateChat.UChat:onServerStart:121]:   at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[14:25:34] [Server thread/INFO] [STDERR]: [br.net.fabiozumbi12.UltimateChat.UChat:onServerStart:121]:   at java.lang.reflect.Method.invoke(Method.java:498)
[14:25:34] [Server thread/INFO] [STDERR]: [br.net.fabiozumbi12.UltimateChat.UChat:onServerStart:121]:   at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
[14:25:34] [Server thread/INFO] [STDERR]: [br.net.fabiozumbi12.UltimateChat.UChat:onServerStart:121]:   at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
[14:25:34] [Server thread/INFO] [STDERR]: [br.net.fabiozumbi12.UltimateChat.UChat:onServerStart:121]:   at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
[14:25:34] [Server thread/INFO] [STDERR]: [br.net.fabiozumbi12.UltimateChat.UChat:onServerStart:121]:   at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
[14:25:34] [Server thread/INFO] [STDERR]: [br.net.fabiozumbi12.UltimateChat.UChat:onServerStart:121]:   at com.google.common.eventbus.EventBus.post(EventBus.java:275)
[14:25:34] [Server thread/INFO] [STDERR]: [br.net.fabiozumbi12.UltimateChat.UChat:onServerStart:121]:   at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:243)
[14:25:34] [Server thread/INFO] [STDERR]: [br.net.fabiozumbi12.UltimateChat.UChat:onServerStart:121]:   at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:221)
[14:25:34] [Server thread/INFO] [STDERR]: [br.net.fabiozumbi12.UltimateChat.UChat:onServerStart:121]:   at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[14:25:34] [Server thread/INFO] [STDERR]: [br.net.fabiozumbi12.UltimateChat.UChat:onServerStart:121]:   at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[14:25:34] [Server thread/INFO] [STDERR]: [br.net.fabiozumbi12.UltimateChat.UChat:onServerStart:121]:   at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[14:25:34] [Server thread/INFO] [STDERR]: [br.net.fabiozumbi12.UltimateChat.UChat:onServerStart:121]:   at java.lang.reflect.Method.invoke(Method.java:498)
[14:25:34] [Server thread/INFO] [STDERR]: [br.net.fabiozumbi12.UltimateChat.UChat:onServerStart:121]:   at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
[14:25:34] [Server thread/INFO] [STDERR]: [br.net.fabiozumbi12.UltimateChat.UChat:onServerStart:121]:   at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
[14:25:34] [Server thread/INFO] [STDERR]: [br.net.fabiozumbi12.UltimateChat.UChat:onServerStart:121]:   at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
[14:25:34] [Server thread/INFO] [STDERR]: [br.net.fabiozumbi12.UltimateChat.UChat:onServerStart:121]:   at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
[14:25:34] [Server thread/INFO] [STDERR]: [br.net.fabiozumbi12.UltimateChat.UChat:onServerStart:121]:   at com.google.common.eventbus.EventBus.post(EventBus.java:275)
[14:25:34] [Server thread/INFO] [STDERR]: [br.net.fabiozumbi12.UltimateChat.UChat:onServerStart:121]:   at net.minecraftforge.fml.common.LoadController.redirect$onPost$zzb000(LoadController.java:552)
[14:25:34] [Server thread/INFO] [STDERR]: [br.net.fabiozumbi12.UltimateChat.UChat:onServerStart:121]:   at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:145)
[14:25:34] [Server thread/INFO] [STDERR]: [br.net.fabiozumbi12.UltimateChat.UChat:onServerStart:121]:   at net.minecraftforge.fml.common.Loader.serverStarted(Loader.java:858)
[14:25:34] [Server thread/INFO] [STDERR]: [br.net.fabiozumbi12.UltimateChat.UChat:onServerStart:121]:   at net.minecraftforge.fml.common.FMLCommonHandler.handleServerStarted(FMLCommonHandler.java:297)
[14:25:34] [Server thread/INFO] [STDERR]: [br.net.fabiozumbi12.UltimateChat.UChat:onServerStart:121]:   at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:433)
[14:25:34] [Server thread/INFO] [STDERR]: [br.net.fabiozumbi12.UltimateChat.UChat:onServerStart:121]:   at java.lang.Thread.run(Thread.java:745)
```
Estou utilizando as seguintes versões do Sponge:
 SpongeForge
    Minecraft: 1.10.2
    SpongeAPI: 5.2.0-SNAPSHOT-a3257a0
    SpongeForge: 1.10.2-2281-5.2.0-BETA-2274

**Comment by FabioZumbi12** [comment]
Arrumado nas ultimas builds: http://areaz12server.net.br:8080/job/UltimateChat/
