### ISSUE TITLE
AsyncPlayerChatEvent to UltimateChat v1.8.8

### ISSUE THREAD

**Issue by Mark154872** [FabioZumbi12/UltimateChat#184]
==> Click on PREVIEW tab!

### Before open an issue, checkout this steps:
* If you are running the plugin at first time, try to run again to see if the problem persists.
* Check if your build is the latest on our Jenkins. Click Here: <https://host.areaz12server.net.br:8080/job/UltimateChat>
* Its important to you include the plugin jar name, because version and build info.

_Put if is the **Spigot** or **Sponge** version._  
Platform: Spigot

_Inform your UltimateChat jar name like **UltimateChat-Spigot-7.0.3.jar**._  
Jar version:  UltimateChat #213 Ultima do discord

_Your server Minecraft version_  
Minecraft version:  1.8.8

_Issue or Suggestion?_  
What you want?:  O plugin nao esta funcionando, vou por o erro aqui que fica melhor para voce entender.

_Describe your issue/Suggestion. If issue, use the site [hastebin.com](https://hastebin.com/) to put your error or console logs._
Description:  

https://hastebin.com/wutaposodi.apache

```ERROR Could not pass event AsyncPlayerChatEvent to UltimateChat v1.8.8
16.03 08:26:25 [Server] INFO org.bukkit.event.EventException
16.03 08:26:25 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[spigot-1.8.8-R0.1-SNAPSHOT.jar:git-Spigot-21fe707-e1ebe52]
16.03 08:26:25 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.8.8-R0.1-SNAPSHOT.jar:git-Spigot-21fe707-e1ebe52]
16.03 08:26:25 [Server] INFO at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot-1.8.8-R0.1-SNAPSHOT.jar:git-Spigot-21fe707-e1ebe52]
16.03 08:26:25 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:484) [spigot-1.8.8-R0.1-SNAPSHOT.jar:git-Spigot-21fe707-e1ebe52]
16.03 08:26:25 [Server] INFO at net.minecraft.server.v1_8_R3.PlayerConnection.chat(PlayerConnection.java:1084) [spigot-1.8.8-R0.1-SNAPSHOT.jar:git-Spigot-21fe707-e1ebe52]
16.03 08:26:25 [Server] INFO at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:1022) [spigot-1.8.8-R0.1-SNAPSHOT.jar:git-Spigot-21fe707-e1ebe52]
16.03 08:26:25 [Server] INFO at net.minecraft.server.v1_8_R3.PacketPlayInChat$1.run(PacketPlayInChat.java:39) [spigot-1.8.8-R0.1-SNAPSHOT.jar:git-Spigot-21fe707-e1ebe52]
16.03 08:26:25 [Server] INFO at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_144]
16.03 08:26:25 [Server] INFO at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_144]
16.03 08:26:25 [Server] INFO at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_144]
16.03 08:26:25 [Server] INFO at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_144]
16.03 08:26:25 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_144]
16.03 08:26:25 [Server] INFO Caused by: java.lang.OutOfMemoryError: Java heap space
16.03 08:26:25 [Server] INFO at java.util.Arrays.copyOf(Arrays.java:3332) ~[?:1.8.0_144]
16.03 08:26:25 [Server] INFO at java.lang.AbstractStringBuilder.ensureCapacityInternal(AbstractStringBuilder.java:124) ~[?:1.8.0_144]
16.03 08:26:25 [Server] INFO at java.lang.AbstractStringBuilder.append(AbstractStringBuilder.java:448) ~[?:1.8.0_144]
16.03 08:26:25 [Server] INFO at java.lang.StringBuffer.append(StringBuffer.java:270) ~[?:1.8.0_144]
16.03 08:26:25 [Server] INFO at org.json.simple.JSONArray.toJSONString(JSONArray.java:91) ~[spigot-1.8.8-R0.1-SNAPSHOT.jar:git-Spigot-21fe707-e1ebe52]
16.03 08:26:25 [Server] INFO at org.json.simple.JSONArray.toJSONString(JSONArray.java:98) ~[spigot-1.8.8-R0.1-SNAPSHOT.jar:git-Spigot-21fe707-e1ebe52]
16.03 08:26:25 [Server] INFO at br.net.fabiozumbi12.UltimateChat.Bukkit.UltimateFancy.toJson(UltimateFancy.java:335) ~[?:?]
16.03 08:26:25 [Server] INFO at br.net.fabiozumbi12.UltimateChat.Bukkit.UltimateFancy.send(UltimateFancy.java:325) ~[?:?]
16.03 08:26:25 [Server] INFO at br.net.fabiozumbi12.UltimateChat.Bukkit.UCMessages.lambda$sendFancyMessage$2(UCMessages.java:241) ~[?:?]
16.03 08:26:25 [Server] INFO at br.net.fabiozumbi12.UltimateChat.Bukkit.UCMessages$$Lambda$291/224597301.accept(Unknown Source) ~[?:?]
16.03 08:26:25 [Server] INFO at java.util.HashMap.forEach(HashMap.java:1288) ~[?:1.8.0_144]
16.03 08:26:25 [Server] INFO at br.net.fabiozumbi12.UltimateChat.Bukkit.UCMessages.sendFancyMessage(UCMessages.java:239) ~[?:?]
16.03 08:26:25 [Server] INFO at br.net.fabiozumbi12.UltimateChat.Bukkit.UCListener.onChat(UCListener.java:893) ~[?:?]
16.03 08:26:25 [Server] INFO at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_144]
16.03 08:26:25 [Server] INFO at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_144]```

**Comment by FabioZumbi12** [comment]
Verifique os seus argumento java, o erro foi devido falta de memoria do java: ` Caused by: java.lang.OutOfMemoryError: Java heap space`

**Comment by Mark154872** [comment]
O servidor esta em um host,como vou verificar ?

**Comment by FabioZumbi12** [comment]
Nao sei dizer, so posso dizer pelo uchat e pelo erro nao eh problema dele e sim de memoria do java. Se pesquisar esse erro ai vai achar isso!

**Comment by Mark154872** [comment]
Certo, obg
