### ISSUE TITLE
[BUG] Change the discord nickname to IN-GAME name

### ISSUE THREAD

**Issue by NyannyWu** [FabioZumbi12/UltimateChat#187]
When trying to sync roles on discord if 

```
  # Change the discord nickname to IN-GAME name?
  to-discord: true
```

Is set to true, roles dont sync and you receive this error

**Screenshots and LOGs**
```
[10:49:26] [Server thread/INFO]: [UltimateChat] JDA connected and ready to use!
[10:49:27] [Craft Scheduler Thread - 328/WARN]: java.lang.NullPointerException
[10:49:27] [Craft Scheduler Thread - 328/WARN]: 	at br.net.fabiozumbi12.UltimateChat.Bukkit.discord.UCDiscord.setPlayerRole(UCDiscord.java:410)
[10:49:27] [Craft Scheduler Thread - 328/WARN]: 	at br.net.fabiozumbi12.UltimateChat.Bukkit.discord.UCDiscordSync.lambda$null$1(UCDiscordSync.java:103)
[10:49:27] [Craft Scheduler Thread - 328/WARN]: 	at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftTask.run(CraftTask.java:84)
[10:49:27] [Craft Scheduler Thread - 328/WARN]: 	at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52)
[10:49:27] [Craft Scheduler Thread - 328/WARN]: 	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[10:49:27] [Craft Scheduler Thread - 328/WARN]: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[10:49:27] [Craft Scheduler Thread - 328/WARN]: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[10:49:27] [Craft Scheduler Thread - 328/WARN]: 	at java.lang.Thread.run(Thread.java:748)
```

**Server and plugins versions (please complete the following information):**
 - Server: Spigot 1.13.2
 - Plugin Version: UltimateChat-1.8.9-b217-Universal.jar
 - Java Version: Java 1.8

**Comment by FabioZumbi12** [comment]
Try the latest dev build and paste the logs again here please.

**Comment by NyannyWu** [comment]
```
[11:52:18] [Craft Scheduler Thread - 913/WARN]: java.lang.NullPointerException
[11:52:18] [Craft Scheduler Thread - 913/WARN]: 	at br.net.fabiozumbi12.UltimateChat.Bukkit.discord.UCDiscord.setPlayerRole(UCDiscord.java:421)
[11:52:18] [Craft Scheduler Thread - 913/WARN]: 	at br.net.fabiozumbi12.UltimateChat.Bukkit.discord.UCDiscordSync.lambda$null$1(UCDiscordSync.java:103)
[11:52:18] [Craft Scheduler Thread - 913/WARN]: 	at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftTask.run(CraftTask.java:84)
[11:52:18] [Craft Scheduler Thread - 913/WARN]: 	at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52)
[11:52:18] [Craft Scheduler Thread - 913/WARN]: 	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[11:52:18] [Craft Scheduler Thread - 913/WARN]: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[11:52:18] [Craft Scheduler Thread - 913/WARN]: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[11:52:18] [Craft Scheduler Thread - 913/WARN]: 	at java.lang.Thread.run(Thread.java:748)
[11:52:18] [Craft Scheduler Thread - 929/WARN]: java.lang.NullPointerException
[11:52:18] [Craft Scheduler Thread - 929/WARN]: 	at br.net.fabiozumbi12.UltimateChat.Bukkit.discord.UCDiscord.setPlayerRole(UCDiscord.java:421)
[11:52:18] [Craft Scheduler Thread - 929/WARN]: 	at br.net.fabiozumbi12.UltimateChat.Bukkit.discord.UCDiscordSync.lambda$null$1(UCDiscordSync.java:103)
[11:52:18] [Craft Scheduler Thread - 929/WARN]: 	at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftTask.run(CraftTask.java:84)
[11:52:18] [Craft Scheduler Thread - 929/WARN]: 	at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52)
[11:52:18] [Craft Scheduler Thread - 929/WARN]: 	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[11:52:18] [Craft Scheduler Thread - 929/WARN]: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[11:52:18] [Craft Scheduler Thread - 929/WARN]: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[11:52:18] [Craft Scheduler Thread - 929/WARN]: 	at java.lang.Thread.run(Thread.java:748)
[11:52:18] [Craft Scheduler Thread - 921/WARN]: java.lang.NullPointerException
[11:52:18] [Craft Scheduler Thread - 921/WARN]: 	at br.net.fabiozumbi12.UltimateChat.Bukkit.discord.UCDiscord.setPlayerRole(UCDiscord.java:421)
[11:52:18] [Craft Scheduler Thread - 921/WARN]: 	at br.net.fabiozumbi12.UltimateChat.Bukkit.discord.UCDiscordSync.lambda$null$1(UCDiscordSync.java:103)
[11:52:18] [Craft Scheduler Thread - 921/WARN]: 	at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftTask.run(CraftTask.java:84)
[11:52:18] [Craft Scheduler Thread - 921/WARN]: 	at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52)
[11:52:18] [Craft Scheduler Thread - 921/WARN]: 	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[11:52:18] [Craft Scheduler Thread - 921/WARN]: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[11:52:18] [Craft Scheduler Thread - 921/WARN]: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[11:52:18] [Craft Scheduler Thread - 921/WARN]: 	at java.lang.Thread.run(Thread.java:748)
[11:52:18] [Craft Scheduler Thread - 904/WARN]: java.lang.NullPointerException
[11:52:18] [Craft Scheduler Thread - 904/WARN]: 	at br.net.fabiozumbi12.UltimateChat.Bukkit.discord.UCDiscord.setPlayerRole(UCDiscord.java:421)
[11:52:18] [Craft Scheduler Thread - 904/WARN]: 	at br.net.fabiozumbi12.UltimateChat.Bukkit.discord.UCDiscordSync.lambda$null$1(UCDiscordSync.java:103)
[11:52:18] [Craft Scheduler Thread - 904/WARN]: 	at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftTask.run(CraftTask.java:84)
[11:52:18] [Craft Scheduler Thread - 904/WARN]: 	at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52)
[11:52:18] [Craft Scheduler Thread - 904/WARN]: 	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[11:52:18] [Craft Scheduler Thread - 904/WARN]: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[11:52:18] [Craft Scheduler Thread - 904/WARN]: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[11:52:18] [Craft Scheduler Thread - 904/WARN]: 	at java.lang.Thread.run(Thread.java:748)
[11:52:18] [Craft Scheduler Thread - 915/WARN]: java.lang.NullPointerException
[11:52:18] [Craft Scheduler Thread - 915/WARN]: 	at br.net.fabiozumbi12.UltimateChat.Bukkit.discord.UCDiscord.setPlayerRole(UCDiscord.java:421)
[11:52:18] [Craft Scheduler Thread - 915/WARN]: 	at br.net.fabiozumbi12.UltimateChat.Bukkit.discord.UCDiscordSync.lambda$null$1(UCDiscordSync.java:103)
[11:52:18] [Craft Scheduler Thread - 915/WARN]: 	at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftTask.run(CraftTask.java:84)
[11:52:18] [Craft Scheduler Thread - 915/WARN]: 	at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52)
[11:52:18] [Craft Scheduler Thread - 915/WARN]: 	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[11:52:18] [Craft Scheduler Thread - 915/WARN]: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[11:52:18] [Craft Scheduler Thread - 915/WARN]: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[11:52:18] [Craft Scheduler Thread - 915/WARN]: 	at java.lang.Thread.run(Thread.java:748)
[11:52:18] [Craft Scheduler Thread - 926/WARN]: java.lang.NullPointerException
[11:52:18] [Craft Scheduler Thread - 926/WARN]: 	at br.net.fabiozumbi12.UltimateChat.Bukkit.discord.UCDiscord.setPlayerRole(UCDiscord.java:421)
[11:52:18] [Craft Scheduler Thread - 926/WARN]: 	at br.net.fabiozumbi12.UltimateChat.Bukkit.discord.UCDiscordSync.lambda$null$1(UCDiscordSync.java:103)
[11:52:18] [Craft Scheduler Thread - 926/WARN]: 	at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftTask.run(CraftTask.java:84)
[11:52:18] [Craft Scheduler Thread - 926/WARN]: 	at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52)
[11:52:18] [Craft Scheduler Thread - 926/WARN]: 	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[11:52:18] [Craft Scheduler Thread - 926/WARN]: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[11:52:18] [Craft Scheduler Thread - 926/WARN]: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[11:52:18] [Craft Scheduler Thread - 926/WARN]: 	at java.lang.Thread.run(Thread.java:748)
```

**Comment by FabioZumbi12** [comment]
Argh, nick return null if not set on discord. Try the latest dev build again.

**Comment by NyannyWu** [comment]
Seems to be working now Thank you!

Do  you think it could be possible to have the ability to decide if it uses the ingame username or the essentials nickname?

**Comment by FabioZumbi12** [comment]
No, because the codes the player can put on essentials nickname.
