### ISSUE TITLE
error

### ISSUE THREAD

**Issue by mat41997** [FabioZumbi12/UltimateChat#19]
log
https://gist.github.com/mat41997/77286c98fe9f276812ebd1fc8a5e205b

timings
https://timings.aikar.co/?id=8a3338730b6d4f5db9aafbe63051ba8a

torch
https://github.com/TorchSpigot/Torch

**Comment by FabioZumbi12** [comment]
The initial log shows this lines:

```
[00:11:02] [Server thread/INFO]: [0;33;22m+ [0;32;1mQiiQii[m

[00:11:12] [Server thread/WARN]: java.lang.NullPointerException

[00:11:12] [Server thread/WARN]: 	at java.lang.String.replace(String.java:2240)

[00:11:12] [Server thread/WARN]: 	at me.loganbwde.lst.OnChat.ClanChat(OnChat.java:438)

[00:11:12] [Server thread/WARN]: 	at me.loganbwde.lst.OnChat.onChat(OnChat.java:213)
```

Seems uChat ir trying to get tag where theres no tags sended, by this plugin. I will check, but open a issue on this plugin issues tracker too.
