### ISSUE TITLE
Possible Ultra Permissions Issue?

### ISSUE THREAD

**Issue by steveabraham** [FabioZumbi12/UltimateChat#207]
Running Paper & Waterfall (1.14.x), with Ultra Permissions.

When I installed UltimateChat, anything at all that's posted to chat causes the following to appear in the console (and nothing outputted to chat):

```
20.06 22:36:36 [Server] WARN [UltimateChat] Task #291 for UltimateChat v1.8.9 generated an exception
20.06 22:36:36 [Server] INFO java.lang.UnsupportedOperationException: SuperPerms no group permissions.
20.06 22:36:36 [Server] INFO at net.milkbowl.vault.permission.plugins.Permission_SuperPerms.getPlayerGroups(Permission_SuperPerms.java:91) ~[?:?]
20.06 22:36:36 [Server] INFO at net.milkbowl.vault.permission.Permission.getPlayerGroups(Permission.java:637) ~[?:?]
20.06 22:36:36 [Server] INFO at br.net.fabiozumbi12.UltimateChat.Bukkit.VaultPerms.getPlayerGroups(UCVaultCache.java:181) ~[?:?]
20.06 22:36:36 [Server] INFO at br.net.fabiozumbi12.UltimateChat.Bukkit.UCMessages.formatTags(UCMessages.java:610) ~[?:?]
20.06 22:36:36 [Server] INFO at br.net.fabiozumbi12.UltimateChat.Bukkit.UCMessages.sendMessage(UCMessages.java:412) ~[?:?]
20.06 22:36:36 [Server] INFO at br.net.fabiozumbi12.UltimateChat.Bukkit.UCMessages.sendFancyMessage(UCMessages.java:115) ~[?:?]
20.06 22:36:36 [Server] INFO at br.net.fabiozumbi12.UltimateChat.Bukkit.UCListener.lambda$onChat$6(UCListener.java:884) ~[?:?]
20.06 22:36:36 [Server] INFO at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftTask.run(CraftTask.java:84) ~[patched_1.14.2.jar:git-Paper-94]
20.06 22:36:36 [Server] INFO at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:452) ~[patched_1.14.2.jar:git-Paper-94]
20.06 22:36:36 [Server] INFO at net.minecraft.server.v1_14_R1.MinecraftServer.b(MinecraftServer.java:1129) ~[patched_1.14.2.jar:git-Paper-94]
20.06 22:36:36 [Server] INFO at net.minecraft.server.v1_14_R1.DedicatedServer.b(DedicatedServer.java:418) ~[patched_1.14.2.jar:git-Paper-94]
20.06 22:36:36 [Server] INFO at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:1061) ~[patched_1.14.2.jar:git-Paper-94]
20.06 22:36:36 [Server] INFO at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:905) ~[patched_1.14.2.jar:git-Paper-94]
20.06 22:36:36 [Server] INFO at java.lang.Thread.run(Thread.java:834) [?:?]
```

**Comment by FabioZumbi12** [comment]
Uchat hook with vault and need vault to work. If you is already using, need to be on latest version.
