### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by Enygmen** [FabioZumbi12/UltimateChat#209]
Não é possível utilizar o plugin.. Ele carrega o plugin mas não é possível enviar mensagens no chat.

Crash:

[Server thread/WARN]: [UltimateChat] Task #1053 for UltimateChat v1.8.9 generated an exception
java.lang.NullPointerException: null
	at java.lang.String.replace(Unknown Source) ~[?:1.8.0_211]
	at br.net.fabiozumbi12.UltimateChat.Bukkit.UCMessages.formatTags(UCMessages.java:621) ~[?:?]
	at br.net.fabiozumbi12.UltimateChat.Bukkit.UCMessages.sendMessage(UCMessages.java:412) ~[?:?]
	at br.net.fabiozumbi12.UltimateChat.Bukkit.UCMessages.sendFancyMessage(UCMessages.java:115) ~[?:?]
	at br.net.fabiozumbi12.UltimateChat.Bukkit.UCListener.lambda$onChat$6(UCListener.java:884) ~[?:?]
	at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftTask.run(CraftTask.java:84) ~[patched_1.14.3.jar:git-Paper-117]
	at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:452) ~[patched_1.14.3.jar:git-Paper-117]
	at net.minecraft.server.v1_14_R1.MinecraftServer.b(MinecraftServer.java:1132) ~[patched_1.14.3.jar:git-Paper-117]
	at net.minecraft.server.v1_14_R1.DedicatedServer.b(DedicatedServer.java:420) ~[patched_1.14.3.jar:git-Paper-117]
	at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:1064) ~[patched_1.14.3.jar:git-Paper-117]
	at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:908) ~[patched_1.14.3.jar:git-Paper-117]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_211]

• Versões de servidor e plug-ins:
 - Servidor: Paper 1.14.3 Build 117
 - Versão do plug-in: UltimateChat-1.8.9-b225-Universal.jar
 - Versão do Java: Java 1.8

![image](https://user-images.githubusercontent.com/52360711/60389635-551bbb80-9a9b-11e9-9741-3809a9aa2772.png)

**Comment by FabioZumbi12** [comment]
Esse erro ai é alguma tag na config que ta com o `format` vazio

**Comment by Enygmen** [comment]
Então Fabio, não modifiquei ele em nada.. Apenas joguei o .jar na pasta plugins... Será que tenho que modificar as configurações? Se possível me chame no Discord Mateus#4150
