### ISSUE TITLE
Could not pass event AsyncPlayerChatEvent to UltimateChat v1.7.1

### ISSUE THREAD

**Issue by Mushu949** [FabioZumbi12/UltimateChat#22]
`[00:14:19 ERROR]: Could not pass event AsyncPlayerChatEvent to UltimateChat v1.7.1
org.bukkit.event.EventException: null
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot.jar:git-Spigot-4df3c0c-03f1e37]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot.jar:git-Spigot-4df3c0c-03f1e37]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:499) [spigot.jar:git-Spigot-4df3c0c-03f1e37]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:484) [spigot.jar:git-Spigot-4df3c0c-03f1e37]
        at br.net.fabiozumbi12.UltimateChat.UCListener.onCmdChat(UCListener.java:298) [UltimateChat-Spigot-1.7.1-b544.jar:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_121]
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_121]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_121]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_121]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) [spigot.jar:git-Spigot-4df3c0c-03f1e37]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) [spigot.jar:git-Spigot-4df3c0c-03f1e37]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:499) [spigot.jar:git-Spigot-4df3c0c-03f1e37]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:484) [spigot.jar:git-Spigot-4df3c0c-03f1e37]
        at net.minecraft.server.v1_12_R1.PlayerConnection.handleCommand(PlayerConnection.java:1377) [spigot.jar:git-Spigot-4df3c0c-03f1e37]
        at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1220) [spigot.jar:git-Spigot-4df3c0c-03f1e37]
        at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:45) [spigot.jar:git-Spigot-4df3c0c-03f1e37]
        at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:1) [spigot.jar:git-Spigot-4df3c0c-03f1e37]
        at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot.jar:git-Spigot-4df3c0c-03f1e37]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_121]
        at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_121]
        at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) [spigot.jar:git-Spigot-4df3c0c-03f1e37]
        at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:747) [spigot.jar:git-Spigot-4df3c0c-03f1e37]
        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:405) [spigot.jar:git-Spigot-4df3c0c-03f1e37]
        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:678) [spigot.jar:git-Spigot-4df3c0c-03f1e37]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:576) [spigot.jar:git-Spigot-4df3c0c-03f1e37]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_121]
Caused by: java.lang.NullPointerException
        at net.milkbowl.vault.chat.plugins.Chat_GroupManager.getPlayerSuffix(Chat_GroupManager.java:285) ~[?:?]
        at net.milkbowl.vault.chat.Chat.getPlayerSuffix(Chat.java:160) ~[?:?]
        at net.milkbowl.vault.chat.Chat.getPlayerSuffix(Chat.java:183) ~[?:?]
        at br.net.fabiozumbi12.UltimateChat.UCMessages.formatTags(UCMessages.java:481) ~[?:?]
        at br.net.fabiozumbi12.UltimateChat.UCMessages.sendFancyMessage(UCMessages.java:296) ~[?:?]
        at br.net.fabiozumbi12.UltimateChat.UCMessages.sendMessage(UCMessages.java:218) ~[?:?]
        at br.net.fabiozumbi12.UltimateChat.UCMessages.sendFancyMessage(UCMessages.java:122) ~[?:?]
        at br.net.fabiozumbi12.UltimateChat.UCListener.onChat(UCListener.java:494) ~[?:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_121]
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_121]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_121]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_121]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[spigot.jar:git-Spigot-4df3c0c-03f1e37]
        ... 25 more`

**Comment by FabioZumbi12** [comment]
http://areaz12server.net.br:8080/job/UltimateChat/
