### ISSUE TITLE
[BUG] UltimateChat v1.8.9 generated an exception

### ISSUE THREAD

**Issue by SrBedrock** [FabioZumbi12/UltimateChat#259]
**Comportamento esperado**
Erro no log.

**Capturas de tela e registros**
```
[21:15:02 WARN]: [UltimateChat] Task #170795 for UltimateChat v1.8.9 generated an exception
java.lang.ArrayIndexOutOfBoundsException: 0
at br.net.fabiozumbi12.UltimateChat.Bukkit.UCMessages.formatTags(UCMessages.java:525) ~[?:?]
at br.net.fabiozumbi12.UltimateChat.Bukkit.UCMessages.sendMessage(UCMessages.java:376) ~[?:?]
at br.net.fabiozumbi12.UltimateChat.Bukkit.UCMessages.lambda$sendFancyMessage$3(UCMessages.java:118) ~[?:?]
at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftTask.run(CraftTask.java:84) ~[patched_1.14.4.jar:git-Paper-240]
at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:452) ~[patched_1.14.4.jar:git-Paper-240]
at net.minecraft.server.v1_14_R1.MinecraftServer.b(MinecraftServer.java:1171) ~[patched_1.14.4.jar:git-Paper-240]
at net.minecraft.server.v1_14_R1.DedicatedServer.b(DedicatedServer.java:417) ~[patched_1.14.4.jar:git-Paper-240]
at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:1098) ~[patched_1.14.4.jar:git-Paper-240]
at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:925) ~[patched_1.14.4.jar:git-Paper-240]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
```

Versões de servidor e plug-ins:
- Servidor: Paper 1.14.4
- Versão do plug-in: UltimateChat-1.8.9-b243-Universal.jar
- Versão do Java:  Java 1.8

**Comment by SrBedrock** [comment]
```>.... [00:00:38 WARN]: [UltimateChat] Task #249379 for UltimateChat v1.8.9 generated an exception
java.lang.ArrayIndexOutOfBoundsException: 0
at br.net.fabiozumbi12.UltimateChat.Bukkit.UCMessages.formatTags(UCMessages.java:525) ~[?:?]
at br.net.fabiozumbi12.UltimateChat.Bukkit.UCMessages.sendMessage(UCMessages.java:412) ~[?:?]
at br.net.fabiozumbi12.UltimateChat.Bukkit.UCMessages.lambda$sendFancyMessage$3(UCMessages.java:118) ~[?:?]
at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftTask.run(CraftTask.java:84) ~[patched_1.15.2.jar:git-Paper-105]
at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:452) ~[patched_1.15.2.jar:git-Paper-105]
at net.minecraft.server.v1_15_R1.MinecraftServer.b(MinecraftServer.java:1185) ~[patched_1.15.2.jar:git-Paper-105]
at net.minecraft.server.v1_15_R1.DedicatedServer.b(DedicatedServer.java:430) ~[patched_1.15.2.jar:git-Paper-105]
at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:1112) ~[patched_1.15.2.jar:git-Paper-105]
at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:934) ~[patched_1.15.2.jar:git-Paper-105]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]```
 
- Servidor: 1.15.2 - Paper-105
 - Versão do plug-in: UltimateChat-1.8.9-b243-Universal.jar

**Comment by SrBedrock** [comment]
Player tenta enviar mensagem no chat local ou global e a mensagem não é enviada no chat e o erro abaixo é enviando no console.
```[23:13:57 WARN]: [UltimateChat] Task #698015 for UltimateChat v1.8.9 generated an exception
java.lang.NullPointerException: null```
