### ISSUE TITLE
[BUG] Console cannot chat

### ISSUE THREAD

**Issue by Coaley** [FabioZumbi12/UltimateChat#266]
I'm using the latest version (b243). For the past few weeks Console wasn't able to send any messages to any channel. This error shows up:
`[13:10:50 WARN]: [UltimateChat] Task #16353 for UltimateChat v1.8.9 generated an exception
java.lang.IllegalStateException: SendChannelMessageEvent may only be triggered asynchronously.
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:545) ~[patched_1.15.2.jar:git-Paper-142]
at br.net.fabiozumbi12.UltimateChat.Bukkit.UCMessages.sendFancyMessage(UCMessages.java:66) ~[?:?]
at br.net.fabiozumbi12.UltimateChat.Bukkit.UCListener.lambda$onCommand$2(UCListener.java:620) ~[?:?]
at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftTask.run(CraftTask.java:84) ~[patched_1.15.2.jar:git-Paper-142]
at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:452) ~[patched_1.15.2.jar:git-Paper-142]
at net.minecraft.server.v1_15_R1.MinecraftServer.b(MinecraftServer.java:1185) ~[patched_1.15.2.jar:git-Paper-142]
at net.minecraft.server.v1_15_R1.DedicatedServer.b(DedicatedServer.java:430) ~[patched_1.15.2.jar:git-Paper-142]
at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:1112) ~[patched_1.15.2.jar:git-Paper-142]
at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:934) ~[patched_1.15.2.jar:git-Paper-142]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_242]`

**Comment by FabioZumbi12** [comment]
Fixed on latest dev builds.
