### ISSUE TITLE
[BUG] Private Message Discord Sync

### ISSUE THREAD

**Issue by Coaley** [FabioZumbi12/UltimateChat#291]
I'm using the latest dev version.
Discord chat sync works, but private messages have stopped being displayed on the given channel (it worked before).

Potential error:
`>.... [13:43:26 ERROR]: [jdalib.jda.internal.requests.WebSocketClient] There was an error in the WebSocket connection
java.lang.NoClassDefFoundError: jdalib/jda/api/requests/CloseCode
at jdalib.jda.internal.requests.WebSocketClient.onDisconnected(WebSocketClient.java:406) ~[?:?]
at com.neovisionaries.ws.client.ListenerManager.callOnDisconnected(ListenerManager.java:224) ~[?:?]
at com.neovisionaries.ws.client.WebSocket.finish(WebSocket.java:3730) ~[?:?]
at com.neovisionaries.ws.client.WebSocket.onThreadsFinished(WebSocket.java:3696) ~[?:?]
at com.neovisionaries.ws.client.WebSocket.onReadingThreadFinished(WebSocket.java:3663) ~[?:?]
at com.neovisionaries.ws.client.ReadingThread.notifyFinished(ReadingThread.java:1138) ~[?:?]
at com.neovisionaries.ws.client.ReadingThread.runMain(ReadingThread.java:80) ~[?:?]
at com.neovisionaries.ws.client.WebSocketThread.run(WebSocketThread.java:45) ~[?:?]`

**Comment by FabioZumbi12** [comment]
It is fixed on latest dev builds
