### ISSUE TITLE
[BUG] PlotSquared triggered WorldCreateEvent and UltimateChat

### ISSUE THREAD

**Issue by TylerS1066** [FabioZumbi12/UltimateChat#332]
**Describe the bug**

**To Reproduce**
1. Install UChat and PlotSquared
2. Set up PlotSquared to load a secondary world with plots

**Expected behavior**
I expect UChat to have no exceptions when PlotSquared loads the plot world.

**Screenshots and LOGs**
After the world is loaded by PlotSquared, the following exception happens in UltimateChat:
```
[13:43:46] [Server thread/INFO]: [UltimateChat] All configurations loaded![m

[13:43:46] [Server thread/INFO]: [UltimateChat] Language file loaded - Using: EN-US[m

[13:43:46] [Server thread/ERROR]: Could not pass event WorldLoadEvent to UltimateChat v1.9.1
org.bukkit.event.EventException

    at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-1.10.2-R0.1-SNAPSHOT-latest.jar:git-Spigot-72c2605-251a5b6]

    at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.10.2-R0.1-SNAPSHOT-latest.jar:git-Spigot-72c2605-251a5b6]

    at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot-1.10.2-R0.1-SNAPSHOT-latest.jar:git-Spigot-72c2605-251a5b6]

    at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot-1.10.2-R0.1-SNAPSHOT-latest.jar:git-Spigot-72c2605-251a5b6]

    at org.bukkit.craftbukkit.v1_10_R1.CraftServer.createWorld(CraftServer.java:939) [spigot-1.10.2-R0.1-SNAPSHOT-latest.jar:git-Spigot-72c2605-251a5b6]

    at org.bukkit.Bukkit.createWorld(Bukkit.java:468) [spigot-1.10.2-R0.1-SNAPSHOT-latest.jar:git-Spigot-72c2605-251a5b6]

    at com.plotsquared.bukkit.util.BukkitSetupUtils.setupWorld(BukkitSetupUtils.java:150) [PlotSquared-3.5.0.jar:?]

    at com.plotsquared.bukkit.BukkitMain.setGenerator(BukkitMain.java:681) [PlotSquared-3.5.0.jar:?]

    at com.intellectualcrafters.plot.PS$3.run(PS.java:289) [PlotSquared-3.5.0.jar:?]

    at org.bukkit.craftbukkit.v1_10_R1.scheduler.CraftTask.run(CraftTask.java:71) [spigot-1.10.2-R0.1-SNAPSHOT-latest.jar:git-Spigot-72c2605-251a5b6]

    at org.bukkit.craftbukkit.v1_10_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:353) [spigot-1.10.2-R0.1-SNAPSHOT-latest.jar:git-Spigot-72c2605-251a5b6]

    at net.minecraft.server.v1_10_R1.MinecraftServer.D(MinecraftServer.java:723) [spigot-1.10.2-R0.1-SNAPSHOT-latest.jar:git-Spigot-72c2605-251a5b6]

    at net.minecraft.server.v1_10_R1.DedicatedServer.D(DedicatedServer.java:400) [spigot-1.10.2-R0.1-SNAPSHOT-latest.jar:git-Spigot-72c2605-251a5b6]

    at net.minecraft.server.v1_10_R1.MinecraftServer.C(MinecraftServer.java:668) [spigot-1.10.2-R0.1-SNAPSHOT-latest.jar:git-Spigot-72c2605-251a5b6]

    at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:567) [spigot-1.10.2-R0.1-SNAPSHOT-latest.jar:git-Spigot-72c2605-251a5b6]

    at java.lang.Thread.run(Unknown Source) [?:1.8.0_241]

Caused by: java.lang.NullPointerException

    at br.net.fabiozumbi12.UltimateChat.Bukkit.UChat.registerAliases(UChat.java:506) ~[?:?]

    at br.net.fabiozumbi12.UltimateChat.Bukkit.UChat.registerAliases(UChat.java:495) ~[?:?]

    at br.net.fabiozumbi12.UltimateChat.Bukkit.UChat.reload(UChat.java:336) ~[?:?]

    at br.net.fabiozumbi12.UltimateChat.Bukkit.UCListener.onCreateWorld(UCListener.java:1038) ~[?:?]

    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_241]

    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_241]

    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_241]

    at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_241]

    at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[spigot-1.10.2-R0.1-SNAPSHOT-latest.jar:git-Spigot-72c2605-251a5b6]

    ... 15 more
```

**Server and plugins versions (please complete the following information):**
 - Server: Spigot 1.10.2
 - Plugin Version: UltimateChat-1.9.1-b265-Universal.jar
 - Java Version: Java 1.8

**Additional context**
This has been tested with both PlotSquared v3.5.0 and v3.823.

**Comment by TylerS1066** [comment]
For reference, earlier in the log it appears that UChat loaded properly:
```
[13:43:43] [Server thread/INFO]: [UltimateChat] Enabling UltimateChat v1.9.1

[13:43:43] [Server thread/INFO]: [UltimateChat] All configurations loaded![m

[13:43:43] [Server thread/INFO]: [UltimateChat] Language file loaded - Using: EN-US[m

[13:43:43] [Server thread/INFO]: [UltimateChat] ProtocolLib found. Hooked.[m

[13:43:43] [Server thread/INFO]: [UltimateChat] Vault economy found. Hooked.[m

[13:43:43] [Server thread/INFO]: [UltimateChat] Vault chat found. Hooked.[m

[13:43:43] [Server thread/INFO]: [UltimateChat] Vault perms found. Hooked.[m

[13:43:43] [Server thread/INFO]: [UltimateChat] Init API module...[m

[13:43:43] [Server thread/INFO]: [UltimateChat] Server Version: 1.10.2-R0.1-SNAPSHOT[m

[13:43:43] [Server thread/INFO]: 

[0;36;1m  _    _ _ _   _                 _        _____ _           _  

 | |  | | | | (_)               | |      / ____| |         | |  

 | |  | | | |_ _ _ __ ___   __ _| |_ ___| |    | |__   __ _| |_ 

 | |  | | | __| | '_ ` _ \ / _` | __/ _ \ |    | '_ \ / _` | __|

 | |__| | | |_| | | | | | | (_| | ||  __/ |____| | | | (_| | |_ 

  \____/|_|\__|_|_| |_| |_|\__,_|\__\___|\_____|_| |_|\__,_|\__|
                                                                
[0;32;1mUltimateChat v1.9.1 enabled!

[m

[13:43:43] [Server thread/INFO]: [UltimateChat] Metrics enabled! See our stats here: https://bstats.org/plugin/bukkit/UltimateChat[m
```
