### ISSUE TITLE
ainda não funciona o @hand

### ISSUE THREAD

**Issue by comonier** [FabioZumbi12/UltimateChat#361]
teste 1: eu digitei /g teste e depois /g @hand
```java
[14:50:21 INFO]: [g] Hu3 comonier ➜ teste
[14:50:26 INFO]: comonier issued server command: /g @hand
```
Separando as mensagens do console em 2 etapas, a primeira referente ao plugin DISCORDSRV que tem a função de enviar qualquer mensagem digitada no chat global para o discord (minecraft to discord)
```java
[14:50:26 INFO]: [DiscordSRV] Plugin UltimateChat v1.9.1 cancelled AsyncPlayerChatEvent (Bukkit) (author: comonier | message: @hand)
[14:50:26 INFO]: [DiscordSRV] [MINECRAFT_TO_DISCORD DEBUG] Chat message received, canceled: true, channel: global
[14:50:26 INFO]: [DiscordSRV] [MINECRAFT_TO_DISCORD DEBUG] User comonier sent a message but it was not delivered to Discord because the chat event was canceled
```
A segunda referente ao próprio comando em sí do @hand:
```java
[14:50:26 WARN]: [UltimateChat] Task #26490 for UltimateChat v1.9.1 generated an exception
java.lang.NullPointerException: Cannot invoke "java.lang.CharSequence.length()" because "sequence" is null
        at com.google.common.base.Utf8.encodedLength(Utf8.java:53) ~[guava-31.0.1-jre.jar:?]
        at br.net.fabiozumbi12.UltimateFancy.UltimateFancy.parseHoverItem(UltimateFancy.java:657) ~[UltimateChat-1.9.1-b294-Universal.jar:?]
        at br.net.fabiozumbi12.UltimateFancy.UltimateFancy.hoverShowItem(UltimateFancy.java:564) ~[UltimateChat-1.9.1-b294-Universal.jar:?]
        at br.net.fabiozumbi12.UltimateChat.Bukkit.UCMessages.sendMessage(UCMessages.java:421) ~[UltimateChat-1.9.1-b294-Universal.jar:?]
        at br.net.fabiozumbi12.UltimateChat.Bukkit.UCMessages.lambda$null$3(UCMessages.java:121) ~[UltimateChat-1.9.1-b294-Universal.jar:?]
        at org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.18.1.jar:git-Paper-76]
        at org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[paper-1.18.1.jar:git-Paper-76]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1547) ~[paper-1.18.1.jar:git-Paper-76]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:480) ~[paper-1.18.1.jar:git-Paper-76]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1470) ~[paper-1.18.1.jar:git-Paper-76]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1264) ~[paper-1.18.1.jar:git-Paper-76]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317) ~[paper-1.18.1.jar:git-Paper-76]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
>
```
O lance de linkar o item da mão com o comando [i] não está tendo nenhum problema, é um plugin que eu tive que instalar enquanto o @hand não funciona:
https://www.spigotmc.org/resources/chatitemdisplay.77177/
Funciona e não da erro no chat não ! 
![image](https://user-images.githubusercontent.com/19571541/146418744-f6906979-6462-4b7e-abb3-896eebc99e85.png)

O que dá erro é o próprio comando /g @hand
essa primeira sequência é referente ao DiscordSRV que está sendo bloqueado pelo ultimatechat de replicar a mensagem para o discord... ( lembrando que o próprio bot do ultimatechat consegue realizar essa função sem problemas ele apenas não permite que o discordsrv também o faça.
```java
[12:06:42 INFO]: comonier issued server command: /g @hand
[12:06:42 INFO]: [DiscordSRV] Plugin UltimateChat v1.9.1 cancelled AsyncPlayerChatEvent (Bukkit) (author: comonier | message: @hand)
[12:06:42 INFO]: [DiscordSRV] [MINECRAFT_TO_DISCORD DEBUG] Chat message received, canceled: true, channel: global
[12:06:42 INFO]: [DiscordSRV] [MINECRAFT_TO_DISCORD DEBUG] User comonier sent a message but it was not delivered to Discord because the chat event was canceled
```
esse segundo conjunto de warns é referente ao problema do @hand
```java
[12:06:42 WARN]: java.lang.ClassNotFoundException: net.minecraft.server.v1_18_R1.ItemStack
[12:06:42 WARN]:        at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:151)
[12:06:42 WARN]:        at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:103)
[12:06:42 WARN]:        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
[12:06:42 WARN]:        at java.base/java.lang.Class.forName0(Native Method)
[12:06:42 WARN]:        at java.base/java.lang.Class.forName(Class.java:375)
[12:06:42 WARN]:        at UltimateChat-1.9.1-b294-Universal.jar//br.net.fabiozumbi12.UltimateFancy.ReflectionUtil.getNMSClass(UltimateFancy.java:814)
[12:06:42 WARN]:        at UltimateChat-1.9.1-b294-Universal.jar//br.net.fabiozumbi12.UltimateFancy.UltimateFancy.convertItemStackToJson(UltimateFancy.java:668)
[12:06:42 WARN]:        at UltimateChat-1.9.1-b294-Universal.jar//br.net.fabiozumbi12.UltimateFancy.UltimateFancy.parseHoverItem(UltimateFancy.java:656)
[12:06:42 WARN]:        at UltimateChat-1.9.1-b294-Universal.jar//br.net.fabiozumbi12.UltimateFancy.UltimateFancy.hoverShowItem(UltimateFancy.java:564)
[12:06:42 WARN]:        at UltimateChat-1.9.1-b294-Universal.jar//br.net.fabiozumbi12.UltimateChat.Bukkit.UCMessages.sendMessage(UCMessages.java:421)
[12:06:42 WARN]:        at UltimateChat-1.9.1-b294-Universal.jar//br.net.fabiozumbi12.UltimateChat.Bukkit.UCMessages.lambda$null$3(UCMessages.java:121)
[12:06:42 WARN]:        at org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftTask.run(CraftTask.java:101)
[12:06:42 WARN]:        at org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483)
[12:06:42 WARN]:        at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1547)
[12:06:42 WARN]:        at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:480)
[12:06:42 WARN]:        at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1470)
[12:06:42 WARN]:        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1264)
[12:06:42 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317)
[12:06:42 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
[12:06:42 WARN]: java.lang.ClassNotFoundException: net.minecraft.server.v1_18_R1.NBTTagCompound
[12:06:42 WARN]:        at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:151)
[12:06:42 WARN]:        at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:103)
[12:06:42 WARN]:        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
[12:06:42 WARN]:        at java.base/java.lang.Class.forName0(Native Method)
[12:06:42 WARN]:        at java.base/java.lang.Class.forName(Class.java:375)
[12:06:42 WARN]:        at UltimateChat-1.9.1-b294-Universal.jar//br.net.fabiozumbi12.UltimateFancy.ReflectionUtil.getNMSClass(UltimateFancy.java:814)
[12:06:42 WARN]:        at UltimateChat-1.9.1-b294-Universal.jar//br.net.fabiozumbi12.UltimateFancy.UltimateFancy.convertItemStackToJson(UltimateFancy.java:669)
[12:06:42 WARN]:        at UltimateChat-1.9.1-b294-Universal.jar//br.net.fabiozumbi12.UltimateFancy.UltimateFancy.parseHoverItem(UltimateFancy.java:656)
[12:06:42 WARN]:        at UltimateChat-1.9.1-b294-Universal.jar//br.net.fabiozumbi12.UltimateFancy.UltimateFancy.hoverShowItem(UltimateFancy.java:564)
[12:06:42 WARN]:        at UltimateChat-1.9.1-b294-Universal.jar//br.net.fabiozumbi12.UltimateChat.Bukkit.UCMessages.sendMessage(UCMessages.java:421)
[12:06:42 WARN]:        at UltimateChat-1.9.1-b294-Universal.jar//br.net.fabiozumbi12.UltimateChat.Bukkit.UCMessages.lambda$null$3(UCMessages.java:121)
[12:06:42 WARN]:        at org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftTask.run(CraftTask.java:101)
[12:06:42 WARN]:        at org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483)
[12:06:42 WARN]:        at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1547)
[12:06:42 WARN]:        at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:480)
[12:06:42 WARN]:        at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1470)
[12:06:42 WARN]:        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1264)
[12:06:42 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317)
[12:06:42 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
[12:06:42 WARN]: java.lang.NullPointerException: Cannot invoke "java.lang.Class.getMethod(String, java.lang.Class[])" because "clazz" is null
[12:06:42 WARN]:        at UltimateChat-1.9.1-b294-Universal.jar//br.net.fabiozumbi12.UltimateFancy.ReflectionUtil.getMethod(UltimateFancy.java:856)
[12:06:42 WARN]:        at UltimateChat-1.9.1-b294-Universal.jar//br.net.fabiozumbi12.UltimateFancy.UltimateFancy.convertItemStackToJson(UltimateFancy.java:670)
[12:06:42 WARN]:        at UltimateChat-1.9.1-b294-Universal.jar//br.net.fabiozumbi12.UltimateFancy.UltimateFancy.parseHoverItem(UltimateFancy.java:656)
[12:06:42 WARN]:        at UltimateChat-1.9.1-b294-Universal.jar//br.net.fabiozumbi12.UltimateFancy.UltimateFancy.hoverShowItem(UltimateFancy.java:564)
[12:06:42 WARN]:        at UltimateChat-1.9.1-b294-Universal.jar//br.net.fabiozumbi12.UltimateChat.Bukkit.UCMessages.sendMessage(UCMessages.java:421)
[12:06:42 WARN]:        at UltimateChat-1.9.1-b294-Universal.jar//br.net.fabiozumbi12.UltimateChat.Bukkit.UCMessages.lambda$null$3(UCMessages.java:121)
[12:06:42 WARN]:        at org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftTask.run(CraftTask.java:101)
[12:06:42 WARN]:        at org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483)
[12:06:42 WARN]:        at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1547)
[12:06:42 WARN]:        at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:480)
[12:06:42 WARN]:        at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1470)
[12:06:42 WARN]:        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1264)
[12:06:42 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317)
[12:06:42 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
[12:06:42 WARN]: [UltimateChat] Task #1355 for UltimateChat v1.9.1 generated an exception
```
```
[14:44:05 WARN]: [UltimateChat] Task #25439 for UltimateChat v1.9.1 generated an exception
java.lang.NullPointerException: Cannot invoke "java.lang.CharSequence.length()" because "sequence" is null
        at com.google.common.base.Utf8.encodedLength(Utf8.java:53) ~[guava-31.0.1-jre.jar:?]
        at br.net.fabiozumbi12.UltimateFancy.UltimateFancy.parseHoverItem(UltimateFancy.java:657) ~[UltimateChat-1.9.1-b294-Universal.jar:?]
        at br.net.fabiozumbi12.UltimateFancy.UltimateFancy.hoverShowItem(UltimateFancy.java:564) ~[UltimateChat-1.9.1-b294-Universal.jar:?]
        at br.net.fabiozumbi12.UltimateChat.Bukkit.UCMessages.sendMessage(UCMessages.java:421) ~[UltimateChat-1.9.1-b294-Universal.jar:?]
        at br.net.fabiozumbi12.UltimateChat.Bukkit.UCMessages.lambda$null$3(UCMessages.java:121) ~[UltimateChat-1.9.1-b294-Universal.jar:?]
        at org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.18.1.jar:git-Paper-76]
        at org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[paper-1.18.1.jar:git-Paper-76]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1547) ~[paper-1.18.1.jar:git-Paper-76]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:480) ~[paper-1.18.1.jar:git-Paper-76]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1470) ~[paper-1.18.1.jar:git-Paper-76]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1264) ~[paper-1.18.1.jar:git-Paper-76]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317) ~[paper-1.18.1.jar:git-Paper-76]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
[14:44:07 INFO]: comonier issued server command: /g teste
[14:44:07 INFO]: [DiscordSRV] Plugin UltimateChat v1.9.1 cancelled AsyncPlayerChatEvent (Bukkit) (author: comonier | message: teste)
[14:44:07 INFO]: [DiscordSRV] [MINECRAFT_TO_DISCORD DEBUG] Chat message received, canceled: true, channel: global
[14:44:07 INFO]: [DiscordSRV] [MINECRAFT_TO_DISCORD DEBUG] User comonier sent a message but it was not delivered to Discord because the chat event was canceled
```
```java
java.lang.NullPointerException: Cannot invoke "java.lang.CharSequence.length()" because "sequence" is null
        at com.google.common.base.Utf8.encodedLength(Utf8.java:53) ~[guava-31.0.1-jre.jar:?]
        at br.net.fabiozumbi12.UltimateFancy.UltimateFancy.parseHoverItem(UltimateFancy.java:657) ~[UltimateChat-1.9.1-b294-Universal.jar:?]
        at br.net.fabiozumbi12.UltimateFancy.UltimateFancy.hoverShowItem(UltimateFancy.java:564) ~[UltimateChat-1.9.1-b294-Universal.jar:?]
        at br.net.fabiozumbi12.UltimateChat.Bukkit.UCMessages.sendMessage(UCMessages.java:421) ~[UltimateChat-1.9.1-b294-Universal.jar:?]
        at br.net.fabiozumbi12.UltimateChat.Bukkit.UCMessages.lambda$null$3(UCMessages.java:121) ~[UltimateChat-1.9.1-b294-Universal.jar:?]
        at org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.18.1.jar:git-Paper-76]
        at org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[paper-1.18.1.jar:git-Paper-76]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1547) ~[paper-1.18.1.jar:git-Paper-76]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:480) ~[paper-1.18.1.jar:git-Paper-76]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1470) ~[paper-1.18.1.jar:git-Paper-76]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1264) ~[paper-1.18.1.jar:git-Paper-76]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317) ~[paper-1.18.1.jar:git-Paper-76]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

**Comment by comonier** [comment]
solved
