### ISSUE TITLE
Não posso falar no chat se estou em um clan do simpleclans [BUG] 

### ISSUE THREAD

**Issue by Abobrah** [FabioZumbi12/UltimateChat#375]
**Antes de abrir um problema, verifique estas etapas:**
* Se você estiver executando o plug-in na primeira vez, tente executar novamente para ver se o problema persiste.
* Verifique se a sua compilação é a mais recente do nosso Jenkins. Clique aqui: <http://host.areaz12server.net.br:8081/job/UltimateChat>
* É importante você incluir o nome do jar do plug-in, porque as informações de versão e construção estão nele.

**Descreva o bug**
Uma descrição clara e concisa do que é o bug.

**Reproduzir**
Etapas para reproduzir o comportamento:
1. Vá para '...'
2. Clique em '....'
3. Role para baixo até '....'
4. Veja o erro

**Comportamento esperado**
Uma descrição clara e concisa do que você esperava que acontecesse.

**Capturas de tela e registros**
Se aplicável, adicione capturas de tela para ajudar a explicar seu problema. Envie seus registros para https://gist.github.com/

**Versões de servidor e plug-ins (preencha as seguintes informações):**
 - Servidor: [por exemplo Sponge 1.12.2, Spigot 1.13.2]
 - Versão do plug-in: [por exemplo UltimateChat-1.8.9-b216-Universal.jar]
 - Versão do Java: [por exemplo Java 1.8]

**Contexto adicional**
Adicione qualquer outro contexto sobre o problema aqui.

Console log apos digitar algo no chat com simple clans 
[13:47:39 WARN]: [UltimateChat] Task #31222 for UltimateChat v1.8.9 generated an exception
java.lang.NoSuchMethodError: 'java.lang.String net.sacredlabyrinth.phaed.simpleclans.managers.SettingsManager.getTagBracketColor()'
        at br.net.fabiozumbi12.UltimateChat.Bukkit.UCMessages.formatTags(UCMessages.java:631) ~[UltimateChat-1.8.9-b235-Universal.jar:?]
        at br.net.fabiozumbi12.UltimateChat.Bukkit.UCMessages.sendMessage(UCMessages.java:413) ~[UltimateChat-1.8.9-b235-Universal.jar:?]
        at br.net.fabiozumbi12.UltimateChat.Bukkit.UCMessages.sendFancyMessage(UCMessages.java:115) ~[UltimateChat-1.8.9-b235-Universal.jar:?]
        at br.net.fabiozumbi12.UltimateChat.Bukkit.UCListener.lambda$onChat$6(UCListener.java:886) ~[UltimateChat-1.8.9-b235-Universal.jar:?]
        at org.bukkit.craftbukkit.v1_19_R2.scheduler.CraftTask.run(CraftTask.java:101) ~[purpur-1.19.3.jar:git-Purpur-1920]
        at org.bukkit.craftbukkit.v1_19_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[purpur-1.19.3.jar:git-Purpur-1920]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1500) ~[purpur-1.19.3.jar:git-Purpur-1920]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:488) ~[purpur-1.19.3.jar:git-Purpur-1920]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1424) ~[purpur-1.19.3.jar:git-Purpur-1920]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1194) ~[purpur-1.19.3.jar:git-Purpur-1920]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:321) ~[purpur-1.19.3.jar:git-Purpur-1920]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]

**Comment by Abobrah** [comment]
Console Log apos digitar algo no chat estando em um clan do simpleclans

[13:47:39 WARN]: [UltimateChat] Task #31222 for UltimateChat v1.8.9 generated an exception
java.lang.NoSuchMethodError: 'java.lang.String net.sacredlabyrinth.phaed.simpleclans.managers.SettingsManager.getTagBracketColor()'
        at br.net.fabiozumbi12.UltimateChat.Bukkit.UCMessages.formatTags(UCMessages.java:631) ~[UltimateChat-1.8.9-b235-Universal.jar:?]
        at br.net.fabiozumbi12.UltimateChat.Bukkit.UCMessages.sendMessage(UCMessages.java:413) ~[UltimateChat-1.8.9-b235-Universal.jar:?]
        at br.net.fabiozumbi12.UltimateChat.Bukkit.UCMessages.sendFancyMessage(UCMessages.java:115) ~[UltimateChat-1.8.9-b235-Universal.jar:?]
        at br.net.fabiozumbi12.UltimateChat.Bukkit.UCListener.lambda$onChat$6(UCListener.java:886) ~[UltimateChat-1.8.9-b235-Universal.jar:?]
        at org.bukkit.craftbukkit.v1_19_R2.scheduler.CraftTask.run(CraftTask.java:101) ~[purpur-1.19.3.jar:git-Purpur-1920]
        at org.bukkit.craftbukkit.v1_19_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[purpur-1.19.3.jar:git-Purpur-1920]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1500) ~[purpur-1.19.3.jar:git-Purpur-1920]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:488) ~[purpur-1.19.3.jar:git-Purpur-1920]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1424) ~[purpur-1.19.3.jar:git-Purpur-1920]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1194) ~[purpur-1.19.3.jar:git-Purpur-1920]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:321) ~[purpur-1.19.3.jar:git-Purpur-1920]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]

**Comment by FabioZumbi12** [comment]
Ja foi arrumado nas ultimas dev builds: [http://host.areaz12server.net.br:8081/job/UltimateChat](http://host.areaz12server.net.br:8081/job/UltimateChat/299/artifact/UltimateChat-Sponge-7/target/UltimateChat-1.9.1-b299-Universal.jar)
