### ISSUE TITLE
[BUG] [CRITICAL] Server hangs when a new user joins and types first message with 5000 lines of that message

### ISSUE THREAD

**Issue by DeSinc** [FabioZumbi12/UltimateChat#380]
**Describe the bug**
When a new user joins the server for the first time and types a message, for some reason Ultimatechat instantly spams ~5000 messages in the chat, hanging the thread completely. The server can still function briefly while this is going on but eventually everyone will lose connection and the entire server will be in a hung state that cannot be ended even with a sudo kill command. It requires a sudo kill -9 on the process to end it.

**To Reproduce**
1. New player joins the server for the first time
2. They type anything in chat, no slash commands just a word "hello" or "thanks" nothing else
3. The server logs now show hundreds if not thousands of logs of this person typing [local] username: hello (see the bottom of the second screenshot below where all the user's messages start getting duplicated into [local] msges a thousand times by ultimatechat)
4. The server hangs and after a little bit all users are disconnected/timed out
5. Only way to stop the server is a force kill

**Expected behavior**
When a new user joins and types a message, it should send a normal message like everyone else, not have 50000 messages be duplicated for 50 pages of logs and hang the server (note: other plugins detect this as spam and kick the user but it does not solve the issue as the spam goes on by Ultimatechat after the user has already been kicked and is not connected anymore)

**Screenshots and LOGs**
If applicable, add screenshots to help explain your problem. Upload your logs to https://gist.github.com/
![image](https://github.com/user-attachments/assets/352131b2-c3e1-4544-9165-dedd1d0976bd)
![image](https://github.com/user-attachments/assets/838907e6-4326-4e14-aed5-5dac6373b688)
(this goes on for like 20-50 pages of spam all taken place inside of a single second)
```
- [Tue 06:48:04 ERROR Minecraft] Could not pass event AsyncPlayerChatEvent to UltimateChat v1.9.2
java.lang.StackOverflowError
    at java.base/java.lang.ClassLoader.defineClass1(Native Method)
    at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1027)
    at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150)
    at java.base/java.net.URLClassLoader.defineClass(URLClassLoader.java:524)
    at java.base/java.net.URLClassLoader$1.run(URLClassLoader.java:427)
    at java.base/java.net.URLClassLoader$1.run(URLClassLoader.java:421)
    at java.base/java.security.AccessController.doPrivileged(AccessController.java:714)
    at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:420)
    at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:593)
    at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526)
    at org.apache.logging.log4j.message.ParameterizedNoReferenceMessageFactory.newMessage(ParameterizedNoReferenceMessageFactory.java:105)
    at org.apache.logging.log4j.message.AbstractMessageFactory.newMessage(AbstractMessageFactory.java:103)
    at org.apache.logging.log4j.spi.AbstractLogger.logMessage(AbstractLogger.java:2713)
    at org.apache.logging.log4j.spi.AbstractLogger.logIfEnabled(AbstractLogger.java:2487)
    at org.apache.logging.log4j.spi.AbstractLogger.warn(AbstractLogger.java:3701)
    at org.apache.logging.log4j.spi.AbstractLogger.handleLogMessageException(AbstractLogger.java:2954)
    at org.apache.logging.log4j.spi.AbstractLogger.tryLogMessage(AbstractLogger.java:2936)
    at org.apache.logging.log4j.spi.AbstractLogger.logMessageTrackRecursion(AbstractLogger.java:2886)
    at org.apache.logging.log4j.spi.AbstractLogger.logMessageSafely(AbstractLogger.java:2868)
    at org.apache.logging.log4j.spi.AbstractLogger.logMessage(AbstractLogger.java:2647)
    at org.apache.logging.log4j.spi.AbstractLogger.logIfEnabled(AbstractLogger.java:2594)
    at org.apache.logging.log4j.spi.AbstractLogger.error(AbstractLogger.java:835)
    at org
```

**Server and plugins versions (please complete the following information):**
 - Server: Paper 1.21.1 build 76
 - Plugin Version: Latest UltimateChat-1.9.2-b303-Universal.jar
 - Also tested latest snapshot UltimateChat-1.9.3-SNAPSHOT-b306-Universal.jar (Aug 17?) from Jenkins
 - Java Version: Java 21

**Comment by FabioZumbi12** [comment]
Can you test with the build 1.9.1 build 300? http://host.areaz12server.net.br:8081/job/UltimateChat/300/

**Comment by DeSinc** [comment]
> Can you test with the build 1.9.1 build 300? http://host.areaz12server.net.br:8081/job/UltimateChat/300/

Sure thing, just spun up a test backup of the server and got the same new user to join and on build 303 it crashed, while testing again on build 300 and it is totally fine:
![image](https://github.com/user-attachments/assets/37a200e2-0907-4b9e-860b-7f5c83d4ff7c)

Here is screenshot of build 303 crashing just to show the backup restore was successful and replicated the bug:
![image](https://github.com/user-attachments/assets/359b6936-5fb1-4a0b-b510-7b18c5ca4e8c)

**Comment by FabioZumbi12** [comment]
On newer versions theres an option to be compatible with DiscordSRV. Please, try to change the `compat` option on config `channel` file (on local first as i see on print), and then on other channel config files, on latest version and see if the problem stills.

**Comment by DeSinc** [comment]
I assume you mean this option as it's the only one:
![image](https://github.com/user-attachments/assets/ca565ee4-45ba-4ecf-831a-3dbaae692632)

Changing this option from false --> true solved the issue! Awesome
