### ISSUE TITLE
[BUG]  Could not pass event AsyncPlayerChatEvent to UltimateChat v1.9.2

### ISSUE THREAD

**Issue by servicomcr** [FabioZumbi12/UltimateChat#381]
Hello,

I am experiencing an issue with the UltimateChat plugin on my server. I am currently running Purpur version 1.21-2284-4e55e26, and the plugin version is UltimateChat-1.9.2.

The error I am encountering is as follows:

[10:34:04 ERROR]: Could not pass event AsyncPlayerChatEvent to UltimateChat v1.9.2
java.lang.IllegalStateException: AsyncPlayerChatEvent may only be triggered asynchronously.
It seems that the AsyncPlayerChatEvent is being triggered synchronously, which is causing this error. Could you please provide guidance on how to resolve this issue or inform me if there is a planned update to fix it?

Thank you for your assistance.

Current Purpur Version: 1.21-2284-4e55e26 (MC: 1.21)*
UltimateChat v1.9.2 y WelcomerPlus v1.1.7-alpha-06.

[10:34:04 ERROR]: Could not pass event AsyncPlayerChatEvent to UltimateChat v1.9.2
java.lang.IllegalStateException: AsyncPlayerChatEvent may only be triggered asynchronously.
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:40) ~[purpur-1.21.jar:1.21-2284-4e55e26]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:131) ~[purpur-1.21.jar:1.21-2284-4e55e26]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628) ~[paper-mojangapi-1.21-R0.1-SNAPSHOT.jar:?]
        at UltimateChat-1.9.2-b303-Universal (1).jar/br.net.fabiozumbi12.UltimateChat.Bukkit.UCListener.onChat(UCListener.java:946) ~[UltimateChat-1.9.2-b303-Universal (1).jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor344.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[paper-mojangapi-1.21-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-mojangapi-1.21-R0.1-SNAPSHOT.jar:1.21-2284-4e55e26]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-mojangapi-1.21-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[purpur-1.21.jar:1.21-2284-4e55e26]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:131) ~[purpur-1.21.jar:1.21-2284-4e55e26]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628) ~[paper-mojangapi-1.21-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.adventure.ChatProcessor.post(ChatProcessor.java:378) ~[purpur-1.21.jar:1.21-2284-4e55e26]
        at io.papermc.paper.adventure.ChatProcessor.process(ChatProcessor.java:85) ~[purpur-1.21.jar:1.21-2284-4e55e26]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.chat(ServerGamePacketListenerImpl.java:2414) ~[purpur-1.21.jar:1.21-2284-4e55e26]
        at org.bukkit.craftbukkit.entity.CraftPlayer.chat(CraftPlayer.java:765) ~[purpur-1.21.jar:1.21-2284-4e55e26]
        at WelcomerPlus-1.1.7-alpha-06.jar/wp.jaina.util.actions.CommandExecutor.executePlayerSend(CommandExecutor.java:148) ~[WelcomerPlus-1.1.7-alpha-06.jar:?]
        at WelcomerPlus-1.1.7-alpha-06.jar/wp.jaina.util.actions.CommandExecutor.executeCommands(CommandExecutor.java:44) ~[WelcomerPlus-1.1.7-alpha-06.jar:?]
        at WelcomerPlus-1.1.7-alpha-06.jar/wp.jaina.util.actions.CommandExecutor.executeCommands(CommandExecutor.java:20) ~[WelcomerPlus-1.1.7-alpha-06.jar:?]
        at WelcomerPlus-1.1.7-alpha-06.jar/wp.jaina.listeners.events.CommandHandler.handleJoinCommands(CommandHandler.java:21) ~[WelcomerPlus-1.1.7-alpha-06.jar:?]
        at WelcomerPlus-1.1.7-alpha-06.jar/wp.jaina.listeners.PlayerListeners.handlePlayerJoin(PlayerListeners.java:79) ~[WelcomerPlus-1.1.7-alpha-06.jar:?]
        at WelcomerPlus-1.1.7-alpha-06.jar/wp.jaina.listeners.PlayerListeners.onJoin(PlayerListeners.java:37) ~[WelcomerPlus-1.1.7-alpha-06.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor321.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[paper-mojangapi-1.21-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-mojangapi-1.21-R0.1-SNAPSHOT.jar:1.21-2284-4e55e26]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-mojangapi-1.21-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[purpur-1.21.jar:1.21-2284-4e55e26]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:131) ~[purpur-1.21.jar:1.21-2284-4e55e26]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628) ~[paper-mojangapi-1.21-R0.1-SNAPSHOT.jar:?]
        at net.minecraft.server.players.PlayerList.placeNewPlayer(PlayerList.java:347) ~[purpur-1.21.jar:1.21-2284-4e55e26]
        at net.minecraft.server.network.ServerConfigurationPacketListenerImpl.handleConfigurationFinished(ServerConfigurationPacketListenerImpl.java:173) ~[purpur-1.21.jar:1.21-2284-4e55e26]
        at net.minecraft.network.protocol.configuration.ServerboundFinishConfigurationPacket.handle(ServerboundFinishConfigurationPacket.java:22) ~[purpur-1.21.jar:1.21-2284-4e55e26]
        at net.minecraft.network.protocol.configuration.ServerboundFinishConfigurationPacket.handle(ServerboundFinishConfigurationPacket.java:13) ~[purpur-1.21.jar:1.21-2284-4e55e26]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:56) ~[purpur-1.21.jar:1.21-2284-4e55e26]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[purpur-1.21.jar:1.21-2284-4e55e26]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:151) ~[purpur-1.21.jar:1.21-2284-4e55e26]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[purpur-1.21.jar:1.21-2284-4e55e26]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1573) ~[purpur-1.21.jar:1.21-2284-4e55e26]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:201) ~[purpur-1.21.jar:1.21-2284-4e55e26]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:125) ~[purpur-1.21.jar:1.21-2284-4e55e26]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1550) ~[purpur-1.21.jar:1.21-2284-4e55e26]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1543) ~[purpur-1.21.jar:1.21-2284-4e55e26]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:135) ~[purpur-1.21.jar:1.21-2284-4e55e26]
        at net.minecraft.server.MinecraftServer.managedBlock(MinecraftServer.java:1502) ~[purpur-1.21.jar:1.21-2284-4e55e26]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1509) ~[purpur-1.21.jar:1.21-2284-4e55e26]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1354) ~[purpur-1.21.jar:1.21-2284-4e55e26]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:333) ~[purpur-1.21.jar:1.21-2284-4e55e26]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]

**Comment by FabioZumbi12** [comment]
Please, try the latest dev build http://host.areaz12server.net.br:8081/job/UltimateChat/lastStableBuild/
