### ISSUE TITLE
Recebo isso as vezes

### ISSUE THREAD

**Issue by Sakanas** [FabioZumbi12/UltimateChat#46]
```
[19:25:52] [Craft Scheduler Thread - 2284/ERROR]: Could not pass event SendChannelMessageEvent to UltimateChat v1.8.4
org.bukkit.event.EventException: null
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-1.12.jar:git-Spigot-596221b-9a1fc1e]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.12.jar:git-Spigot-596221b-9a1fc1e]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:499) [spigot-1.12.jar:git-Spigot-596221b-9a1fc1e]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:484) [spigot-1.12.jar:git-Spigot-596221b-9a1fc1e]
	at br.net.fabiozumbi12.UltimateChat.Bukkit.UCMessages.sendFancyMessage(UCMessages.java:41) [UltimateChat-1.8.4-b109-Universal.jar:?]
	at br.net.fabiozumbi12.UltimateChat.Bukkit.UCListener.sendTell(UCListener.java:681) [UltimateChat-1.8.4-b109-Universal.jar:?]
	at br.net.fabiozumbi12.UltimateChat.Bukkit.UCListener.onChat(UCListener.java:714) [UltimateChat-1.8.4-b109-Universal.jar:?]
	at sun.reflect.GeneratedMethodAccessor942.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_91]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_91]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) [spigot-1.12.jar:git-Spigot-596221b-9a1fc1e]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) [spigot-1.12.jar:git-Spigot-596221b-9a1fc1e]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:499) [spigot-1.12.jar:git-Spigot-596221b-9a1fc1e]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:481) [spigot-1.12.jar:git-Spigot-596221b-9a1fc1e]
	at br.net.fabiozumbi12.UltimateChat.Bukkit.UCListener$4.run(UCListener.java:640) [UltimateChat-1.8.4-b109-Universal.jar:?]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:71) [spigot-1.12.jar:git-Spigot-596221b-9a1fc1e]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) [spigot-1.12.jar:git-Spigot-596221b-9a1fc1e]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_91]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_91]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_91]
Caused by: java.lang.NullPointerException
	at br.net.fabiozumbi12.UltimateChat.Bukkit.UCChatProtection.onPlayerChat(UCChatProtection.java:46) ~[?:?]
	at sun.reflect.GeneratedMethodAccessor946.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_91]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_91]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[spigot-1.12.jar:git-Spigot-596221b-9a1fc1e]
	... 19 more
```

**Comment by FabioZumbi12** [comment]
Tenta a ultima build do jenkins, na descrição daqui do github tem o link, e ve se resolve.
