### ISSUE TITLE
Discord Integration causing plugin Failure (Part Resolved)

### ISSUE THREAD

**Issue by NiNjAiKoToBa** [FabioZumbi12/UltimateChat#58]
==> Click on PREVIEW tab!

### Before open an issue, checkout this steps:
* If you are running the plugin at first time, try to run again to see if the problem persists.
* Check if your build is the latest on our Jenkins. Click Here: <http://areaz12server.net.br:8080/job/UltimateChat>
* Its important to you include the plugin jar name, because version and build info.

_Put if is the **Spigot** or **Sponge** version._  
Plataform:  Spigot

_Inform your UltimateChat jar name like **UltimateChat-Spigot-7.0.3.jar**._  
Jar version:  UltimateChat-1.8.4-b116-Universal.jar

_Your server Minecraft version_  
Minecraft version:  1.12

_Issue or Suggestion?_  
What you want?:  Issue, I'm looking for a fix.

_Descript your issue/Suggestion. If issue, use the site [hastebin.com](https://hastebin.com/) to put your error or console logs._  
Description:  The plugin wont load on my server for some reason when i have Discord Mode enabled in the Config.yml file. I have no idea why. Is this a conflict? The plugin works fine when Discord mode is set to false. This issue did not occur on a test server with no other plugins installed.

[04:02:08] [Server thread/INFO]: [UltimateChat] Enabling UltimateChat v1.8.4
[04:02:08] [Server thread/WARN]: Enabled plugin with unregistered PluginClassLoader UltimateChat v1.8.4
[04:02:08] [Server thread/INFO]: UltimateChat: [All configurations loaded!]
[04:02:08] [Server thread/INFO]: UltimateChat: [Language file loaded - Using: EN-US]
[04:02:08] [Server thread/INFO]: UltimateChat: [ProtocolLib found. Hooked.]
[04:02:08] [Server thread/INFO]: UltimateChat: [PlaceHolderAPI found. Hooked and registered some chat placeholders.]
[04:02:08] [Server thread/INFO]: UltimateChat: [Vault economy found. Hooked.]
[04:02:08] [Server thread/INFO]: UltimateChat: [Vault chat found. Hooked.]
[04:02:08] [Server thread/INFO]: UltimateChat: [Vault perms found. Hooked.]
[04:02:08] [Server thread/INFO]: UltimateChat: [Init API module...]
[04:02:08] [Server thread/INFO]: UltimateChat: [JDA LibLoader is present...]
[04:02:08] [Server thread/ERROR]: [UltimateChat] The TOKEN is wrong or empty! Check you config and your token.
[04:02:08] [Server thread/INFO]: UltimateChat: [Server Version: 1.12-R0.1-SNAPSHOT]
[04:02:08] [Server thread/INFO]: 
  _    _ _ _   _                 _        _____ _           _  
 | |  | | | | (_)               | |      / ____| |         | |  
 | |  | | | |_ _ _ __ ___   __ _| |_ ___| |    | |__   __ _| |_ 
 | |  | | | __| | '_ ` _ \ / _` | __/ _ \ |    | '_ \ / _` | __|
 | |__| | | |_| | | | | | | (_| | ||  __/ |____| | | | (_| | |_ 
  \____/|_|\__|_|_| |_| |_|\__,_|\__\___|\_____|_| |_|\__,_|\__|
                                                                
UltimateChat v1.8.4 enabled!

[04:02:08] [Server thread/WARN]: java.lang.NullPointerException
[04:02:08] [Server thread/WARN]: 	at br.net.fabiozumbi12.UltimateChat.Bukkit.UCDiscord.sendToChannel(UCDiscord.java:160)
[04:02:08] [Server thread/WARN]: 	at br.net.fabiozumbi12.UltimateChat.Bukkit.UCDiscord.sendRawToDiscord(UCDiscord.java:142)
[04:02:08] [Server thread/WARN]: 	at br.net.fabiozumbi12.UltimateChat.Bukkit.UChat.onEnable(UChat.java:243)
[04:02:08] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
[04:02:08] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:316)
[04:02:08] [Server thread/WARN]: 	at com.massivecraft.massivelag.inject.MassiveLagPluginLoader.enablePlugin(MassiveLagPluginLoader.java:215)
[04:02:08] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:404)
[04:02:08] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:376)
[04:02:08] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:325)
[04:02:08] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:441)
[04:02:08] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:402)
[04:02:08] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:340)
[04:02:08] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:290)
[04:02:08] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:615)
[04:02:08] [Server thread/WARN]: 	at java.lang.Thread.run(Thread.java:748)
[04:02:08] [Server thread/ERROR]: Error occurred while enabling UltimateChat v1.8.4 (Is it up to date?)
java.lang.NullPointerException: null
	at br.net.fabiozumbi12.UltimateChat.Bukkit.UCDiscord.sendToChannel(UCDiscord.java:160) ~[?:?]
	at br.net.fabiozumbi12.UltimateChat.Bukkit.UCDiscord.sendRawToDiscord(UCDiscord.java:142) ~[?:?]
	at br.net.fabiozumbi12.UltimateChat.Bukkit.UChat.onDisable(UChat.java:392) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:266) ~[spigot.jar:git-Paper-1169]
	at br.net.fabiozumbi12.UltimateChat.Bukkit.UChat.onEnable(UChat.java:247) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[spigot.jar:git-Paper-1169]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:316) [spigot.jar:git-Paper-1169]
	at com.massivecraft.massivelag.inject.MassiveLagPluginLoader.enablePlugin(MassiveLagPluginLoader.java:215) [MassiveLag.jar:?]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:404) [spigot.jar:git-Paper-1169]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:376) [spigot.jar:git-Paper-1169]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:325) [spigot.jar:git-Paper-1169]
	at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:441) [spigot.jar:git-Paper-1169]
	at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:402) [spigot.jar:git-Paper-1169]
	at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:340) [spigot.jar:git-Paper-1169]
	at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:290) [spigot.jar:git-Paper-1169]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:615) [spigot.jar:git-Paper-1169]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_151]

**Comment by FabioZumbi12** [comment]
You have enabled JDA on your config, but the token is wrong!

**Comment by NiNjAiKoToBa** [comment]
I have checked my discord token, but it is correct as DiscordSRV can load it, and the plugin is working fine on my test server. If i startup the server, then use a pluginloader to load the plugin post server launch with the same config, then it loads fine. For some reason its just refusing the load when i load it as part of a normal boot? I have no idea why its happening, but the Token is definitley correct.

**Comment by FabioZumbi12** [comment]
Well, if loads in your test server, there's nothing wrong with the plugin. In a isolated case, can have a compat issue with other plugins using discord link too, but i dont know in whats cases, as i never had this issue before.

**Comment by NiNjAiKoToBa** [comment]
I am going to work on this, and i’ll let you know what the conflict is when i find it.

**Comment by NiNjAiKoToBa** [comment]
The new version/dev build you have released sorta solves this problem. The plugin no longer dies upon start, but typing /chat reload suddenly makes discord integration work asif nothing is wrong?

Its a bit weird. It says the token is wrong on startup, but accepts it on a reload. Is there any way to make it recheck the key after startup automatically, or maybe when a player manually enters a Discord Enabled channel if they key wasnt accepted before?

**Comment by FabioZumbi12** [comment]
Seems when your server is loading and for some reason rejects because other plugin is using connection, or your server only accepts only out connection to same udp port...

**Comment by NiNjAiKoToBa** [comment]
For now i'm using a workaround by scheduling my server to run "/chat reload" 5 minutes after the daily server reboot, and thats doing the trick. I hate trying t solve conflicts on a life server as the test servers never seem to give the same results >.>

**Comment by FabioZumbi12** [comment]
Few questions to investigate the problem:

- Using VM or dedicated (to known about firewall);
- Confirm if using Firewall and if is blocking certain amount of out connections (maybe your machine allow only one connection to the discord api);
- Try to see the connections with a monitor or similiar tool to check the connections to discord api (sorry, i dont known the discord api IP, try to see java connections on startup of your server);
- Compare the connections (using the tool) when you use the `/reload` command;

This is just to we know what can be causing this issue because i still dont know how to "fix", and if need to be fixed with UChat or your server/connection.

**Comment by n0dai** [comment]
If you are using LiteBans, remove it and try.
