### ISSUE TITLE
Incompatiblity with Spigot Plugin: CharsAPI

### ISSUE THREAD

**Issue by MrMurfy** [FabioZumbi12/UltimateChat#74]
Plataform:  Spigot 1.12.2 (latest version of BuildTools)

Jar version:  UltimateChat-1.8.3_b97.jar (Build 97)

Minecraft version:  1.12.2

What you want?:  I found an incompatibility with the plugin [CharsAPI](https://www.spigotmc.org/resources/charsapi.3439/) . It might be because of the use of the same command '/ch '. So I would like to know what can I do in order to could use both plugins.

**Comment by MrMurfy** [comment]
I have tried to remove CharsAPI, and then appears an error in console:
`[Server thread/ERROR]: Could not load 'plugins\UltimateChat-1.8.3-b97-Universal.jar' in folder 'plugins'
org.bukkit.plugin.InvalidDescriptionException: Invalid plugin.yml
	at org.bukkit.plugin.java.JavaPluginLoader.getPluginDescription(JavaPluginLoader.java:160) ~[spigot-1.12.2.jar:git-Spigot-549c1fa-45c8386]
	at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:133) [spigot-1.12.2.jar:git-Spigot-549c1fa-45c8386]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.loadPlugins(CraftServer.java:306) [spigot-1.12.2.jar:git-Spigot-549c1fa-45c8386]
	at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:205) [spigot-1.12.2.jar:git-Spigot-549c1fa-45c8386]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:545) [spigot-1.12.2.jar:git-Spigot-549c1fa-45c8386]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_151]
Caused by: java.util.zip.ZipException: zip file is empty
	at java.util.zip.ZipFile.open(Native Method) ~[?:1.8.0_151]
	at java.util.zip.ZipFile.<init>(Unknown Source) ~[?:1.8.0_151]
	at java.util.zip.ZipFile.<init>(Unknown Source) ~[?:1.8.0_151]
	at java.util.jar.JarFile.<init>(Unknown Source) ~[?:1.8.0_151]
	at java.util.jar.JarFile.<init>(Unknown Source) ~[?:1.8.0_151]
	at org.bukkit.plugin.java.JavaPluginLoader.getPluginDescription(JavaPluginLoader.java:148) ~[spigot-1.12.2.jar:git-Spigot-549c1fa-45c8386]
	... 5 more`

Also, I have tried to use another version (UltimateChat-1.8.2-b88) but it doesnt let me use the command '/ch '. A message appears saying to use '/<canal><msg> - Envia mensagem sem entrar no canal'

**Comment by Christiano322** [comment]
Your version of ultimate chat is outdated (This version looks like the plugin.yml is wrong), try to download the latest build on jenkins. (http://areaz12server.net.br:8080/job/UltimateChat/lastStableBuild/)

**Comment by MrMurfy** [comment]
Yep, I'd tried that, but the incompatibility with CharsAPI is still there

**Comment by FabioZumbi12** [comment]
As an Api, I thing his commands is of lower importance comparing with chat commands.

Talk to CharsAPI to change his commands (or you can open the jar and change the command on plugin.yml).
