### ISSUE TITLE
Error when sending message in chat

### ISSUE THREAD

**Issue by pingvikin** [FabioZumbi12/UltimateChat#75]
_Plataform:_  spongeforge-1.12.2-2555-7.0.0-BETA-2799

_Jar version:_  UltimateChat-1.8.4-b130-Universal.jar

_Minecraft version:_  1.12.2

_What i want?:_  I installed this plugin, and i have errors when players sending messages in chat.

_Description:_ 
[23:41:22] [Server thread/ERROR] [Sponge]: Could not pass MessageChannelEvent$Chat$Impl to Plugin{id=ultimatechat, name=UltimateChat, version=1.8.4, description=Complete and advanced chat plugin, authors=[FabioZumbi12], source=/opt/msm/servers/newsigma/mods/UltimateChat-1.8.4-b130-Universal.jar}
java.lang.NoClassDefFoundError: org/spongepowered/api/event/cause/NamedCause
        at io.github.flibio.economylite.CauseFactory.create(CauseFactory.java:34) ~[CauseFactory.class:?]
        at io.github.flibio.economylite.impl.economy.LiteEconomyService.getOrCreateAccount(LiteEconomyService.java:58) ~[LiteEconomyService.class:?]
        at br.net.fabiozumbi12.UltimateChat.Sponge.UCMessages.formatTags(UCMessages.java:637) ~[UCMessages.class:?]
        at br.net.fabiozumbi12.UltimateChat.Sponge.UCMessages.sendMessage(UCMessages.java:417) ~[UCMessages.class:?]
        at br.net.fabiozumbi12.UltimateChat.Sponge.UCMessages.sendFancyMessage(UCMessages.java:101) ~[UCMessages.class:?]
        at br.net.fabiozumbi12.UltimateChat.Sponge.UCListener.onChat(UCListener.java:110) ~[UCListener.class:?]
        at org.spongepowered.common.event.listener.ChatListener_UCListener_onChat127.handle(Unknown Source) ~[?:?]
        at org.spongepowered.common.event.RegisteredListener.handle(RegisteredListener.java:95) ~[RegisteredListener.class:1.12.2-2555-7.0.0-BETA-2799]
        at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:328) [SpongeModEventManager.class:1.12.2-2555-7.0.0-BETA-2799]
        at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:276) [SpongeModEventManager.class:1.12.2-2555-7.0.0-BETA-2799]
        at net.minecraftforge.fml.common.eventhandler.EventBus.postForgeAndCreateSpongeEvent(EventBus.java:601) [EventBus.class:?]
        at net.minecraft.network.NetHandlerPlayServer.handler$injectChatEvent$zpm000(NetHandlerPlayServer.java:2729) [pa.class:?]
        at net.minecraft.network.NetHandlerPlayServer.func_147354_a(NetHandlerPlayServer.java:942) [pa.class:?]
        at net.minecraft.network.play.client.CPacketChatMessage.func_148833_a(SourceFile:37) [la.class:?]
        at net.minecraft.network.play.client.CPacketChatMessage.func_148833_a(SourceFile:9) [la.class:?]
        at org.spongepowered.common.network.PacketUtil.onProcessPacket(PacketUtil.java:149) [PacketUtil.class:1.12.2-2555-7.0.0-BETA-2799]
        at net.minecraft.network.PacketThreadUtil$1.redirect$onProcessPacket$zjp000(SourceFile:539) [hv$1.class:?]
        at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) [hv$1.class:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_72]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_72]
        at net.minecraft.util.Util.func_181617_a(SourceFile:46) [h.class:?]
        at org.spongepowered.common.SpongeImplHooks.onUtilRunTask(SpongeImplHooks.java:274) [SpongeImplHooks.class:1.12.2-2555-7.0.0-BETA-2799]
        at net.minecraft.server.MinecraftServer.redirect$onRun$zif000(MinecraftServer.java:4007) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:721) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:396) [nz.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:666) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_72]
Caused by: java.lang.ClassNotFoundException: org.spongepowered.api.event.cause.NamedCause
        at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191) ~[launchwrapper-1.12.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_72]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_72]
        ... 28 more
Caused by: java.lang.NullPointerException

**Comment by FabioZumbi12** [comment]
`java.lang.NoClassDefFoundError: org/spongepowered/api/event/cause/NamedCause
at io.github.flibio.economylite.CauseFactory.create(CauseFactory.java:34)`

Update EconomyLite to latest version.

**Comment by pingvikin** [comment]
Thank you very much, everything works
