### ISSUE TITLE
Could not pass event AsyncPlayerChatEvent to UltimateChat v1.8.3

### ISSUE THREAD

**Issue by caiovrcombat** [FabioZumbi12/UltimateChat#76]
Coloquei o plugin mas o formato do chat não muda. os comandos do tipo "/admin" "/g" funcionam, porém o formato continua padrão do minecraft

[17:09:58] [Async Chat Thread - #1/ERROR]: Could not pass event AsyncPlayerChatEvent to UltimateChat v1.8.3
org.bukkit.event.EventException: null
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-1.12.2.jar:git-Spigot-7754231-9a1f5ee]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.12.2.jar:git-Spigot-7754231-9a1f5ee]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:499) [spigot-1.12.2.jar:git-Spigot-7754231-9a1f5ee]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:481) [spigot-1.12.2.jar:git-Spigot-7754231-9a1f5ee]
	at net.minecraft.server.v1_12_R1.PlayerConnection.chat(PlayerConnection.java:1314) [spigot-1.12.2.jar:git-Spigot-7754231-9a1f5ee]
	at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1252) [spigot-1.12.2.jar:git-Spigot-7754231-9a1f5ee]
	at net.minecraft.server.v1_12_R1.PacketPlayInChat$1.run(PacketPlayInChat.java:39) [spigot-1.12.2.jar:git-Spigot-7754231-9a1f5ee]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_72]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_72]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_72]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_72]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_72]
Caused by: java.lang.UnsupportedOperationException: SuperPerms no group permissions.
	at net.milkbowl.vault.permission.plugins.Permission_SuperPerms.getPlayerGroups(Permission_SuperPerms.java:91) ~[?:?]
	at net.milkbowl.vault.permission.Permission.getPlayerGroups(Permission.java:684) ~[?:?]
	at br.net.fabiozumbi12.UltimateChat.Bukkit.UCMessages.formatTags(UCMessages.java:514) ~[?:?]
	at br.net.fabiozumbi12.UltimateChat.Bukkit.UCMessages.sendMessage(UCMessages.java:333) ~[?:?]
	at br.net.fabiozumbi12.UltimateChat.Bukkit.UCMessages.sendFancyMessage(UCMessages.java:87) ~[?:?]
	at br.net.fabiozumbi12.UltimateChat.Bukkit.UCListener.onChat(UCListener.java:756) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_72]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_72]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_72]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_72]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[spigot-1.12.2.jar:git-Spigot-7754231-9a1f5ee]
	... 11 more

**Comment by FabioZumbi12** [comment]
```
Caused by: java.lang.UnsupportedOperationException: SuperPerms no group permissions.
at net.milkbowl.vault.permission.plugins.Permission_SuperPerms.getPlayerGroups(Permission_SuperPerms.java:91) 
```
Atualiza seu plugin de permissões, o erro é nele ou no vault.

**Comment by caiovrcombat** [comment]
Existe algum plugin de permissão para 1.12?

**Comment by FabioZumbi12** [comment]
PermissionsEx, LuckPerms, GroupManager... todos funcionam na 1.12

**Comment by caiovrcombat** [comment]
Pra colocar em portugues é só colocar na config o PT-BR?
